$(()=>{
    var uname=$("#main #uname"),upwd=$("#upwd"),yzm=$("#yzm"),progress_p=0,progress_agree=0;
    //验证用户名是否可用
    function checkName(e){
        return new Promise(callback=>{
            var u=e.val().trim();
            if(u!=""){
                $.ajax({
                    type:"post",
                    url:"data/routes/users/checkName.php",
                    data:{uname:u},
                    dataType:"text",
                    success:function(data){
                        if(data=="false"){
                            e.next().html("该用户名已被占用,请更换").css("color","#f00");
                        }else{
                            e.next().html("该用户名可用").css("color","#f00");
                            callback();
                        }
                    },
                    error:function(){
                        alert("网络故障请重试!");
                    }
                })
            }
        })
    }
    //验证重复密码是否一致
    function checkPwds(e){
        if(e.val().trim()!=$("#upwd").val().trim()){
            e.next().html("两次输入不一致,请重新输入!").css("color","#f00");
            if(progress_p==0){
                return;
            }else{
                progress_p-=50;
                $("#btnReg").attr("disabled",true);
            }
        }else{
            e.next().html("密码一致~").css("color","#f00");
            if(progress_p==0){
                progress_p+=50;
                if(progress_p==50&&progress_agree==50){
                    $("#btnReg").attr("disabled",false);
                }
            }
        }
    }
    //用户名框失去焦点
    $("#main #uname").blur(e=>{
        if($(e.target).val().trim()==""){
            $(e.target).next().html("用户名不能为空").css("color","#f00");
        }else{
            checkName($(e.target));
        }
    });
    //密码框失去焦点
    $("#upwd").blur(e=>{
        if($(e.target).val().trim()==""){
            $(e.target).next().html("密码不能为空").css("color","#f00");
        }
    });
    //重复密码框失去焦点
    $("#Pwds").blur(e=>{
        if($(e.target).val().trim()==""){
            $(e.target).next().html("重复密码不能为空").css("color","#f00");
        }else{
            checkPwds($(e.target));
        }
    });
    //是否同意协议
    $(".agreement>sup").on("click",function(){
        if(!$(this).hasClass("active")){
            $(this).addClass("active");
            if(progress_agree==0){
                progress_agree+=50;
                if(progress_p==50&&progress_agree==50){
                    $("#btnReg").attr("disabled",false);
                }
            }
        }else if($(this).hasClass("active")){
            $(this).removeClass("active");
            if(progress_agree==50){
                progress_agree-=50;
                $("#btnReg").attr("disabled",true);
            }
        }
    });
    //点击注册
    $("#btnReg").click(()=>{
        console.log("可以注册");
        var u=$(uname).val().trim(),
            p=$(upwd).val().trim(),
            y=$(yzm).val().trim(),
            uReg=/^[a-zA-Z0-9_]{6,12}$/i,
            pReg=/^[a-zA-Z0-9_]{6,12}$/i,
            yzmReg=/^[a-zA-Z]{4}$/i;
        if(y==""){
            $(yzm).next().html("验证码不能为空").css("color","#f00");
            return;
        }
        if(!uReg.test(u)){
            $(uname).next().html("用户名格式不正确,请检查后重试").css("color","#f00");
            return;
        }
        if(!pReg.test(p)){
            $(upwd).next().html("密码格式不正确,请检查后重试").css("color","#f00");
            return;
        }
        if(!yzmReg.test(y)){
            $(yzm).next().html("验证码格式不正确,请检查后重试").css("color","#f00");
            return;
        }
        checkName(uname).then(()=>{
            $.ajax({
                type:"post",
                url:"data/routes/users/register.php",
                data:{uname:u,upwd:p,yzm:y},
                dataType:"json",
                success:function(data){
                    alert(data.msg);
                    if(data.code==1){
                        //location="index.html";
                    }
                },
                error:function(){
                    alert("网络故障请重试!");
                }
            })
        })
    });
    //点击验证码更换图片
    $("#setYzm").click(function(){
        this.src="data/03_code_gg.php";
    });
});