SET NAMES UTF8;
DROP DATABASE IF EXISTS mcake;
CREATE DATABASE mcake CHARSET=UTF8;
USE mcake;

#1 用户信息表 mc_user
CREATE TABLE mc_user(
	uid INT PRIMARY KEY AUTO_INCREMENT,
	uname VARCHAR(32),
	upwd VARCHAR(32),
	phone VARCHAR(16) NOT NULL DEFAULT '',
	avatar VARCHAR(128) DEFAULT "Images/avatar/default.png",
	user_name VARCHAR(32) DEFAULT "",
	gender INT	DEFAULT 1                   #0-女 1-男
);

INSERT INTO mc_user VALUES
(null,'dongdong',md5('123456'),'13901234561',default,default,default);

INSERT INTO mc_user VALUES
(null,'glorification',md5('123456'),'13901234561',default,default,default),
(null,'forget',md5('123456'),'13901234561',default,default,default),
(null,'remember',md5('123456'),'13901234561',default,default,default),
(null,'principle',md5('123456'),'13901234561',default,default,default),
(null,'gencontre',md5('123456'),'13901234561',default,default,default),
(null,'goodnIght',md5('123456'),'13901234561',default,default,default),
(null,'dream',md5('123456'),'13901234561',default,default,default),
(null,'demon',md5('123456'),'13901234561',default,default,default),
(null,'seven',md5('123456'),'13901234561',default,default,default),
(null,'jonathan',md5('123456'),'13901234561',default,default,default),
(null,'desolate',md5('123456'),'13901234561',default,default,default),
(null,'Sadness',md5('123456'),'13901234561',default,default,default),
(null,'whiteIn',md5('123456'),'13901234561',default,default,default),
(null,'uranus',md5('123456'),'13901234561',default,default,default),
(null,'foreboding',md5('123456'),'13901234561',default,default,default),
(null,'affliction',md5('123456'),'13901234561',default,default,default),
(null,'asphyxia',md5('123456'),'13901234561',default,default,default),
(null,'flustered',md5('123456'),'13901234561',default,default,default),
(null,'layoomiety',md5('123456'),'13901234561',default,default,default),
(null,'latitude',md5('123456'),'13901234561',default,default,default),
(null,'monlogue',md5('123456'),'13901234561',default,default,default),
(null,'eleanore',md5('123456'),'13901234561',default,default,default),
(null,'warming',md5('123456'),'13901234561',default,default,default),
(null,'summer',md5('123456'),'13901234561',default,default,default),
(null,'sakitam',md5('123456'),'13901234561',default,default,default),
(null,'extreme',md5('123456'),'13901234561',default,default,default),
(null,'sunny',md5('123456'),'13901234561',default,default,default),
(null,'emily',md5('123456'),'13901234561',default,default,default),
(null,'shirley',md5('123456'),'13901234561',default,default,default),
(null,'vivian',md5('123456'),'13901234561',default,default,default),
(null,'joyce',md5('123456'),'13901234561',default,default,default),
(null,'nancy',md5('123456'),'13901234561',default,default,default),
(null,'candy',md5('123456'),'13901234561',default,default,default),
(null,'melody',md5('123456'),'13901234561',default,default,default),
(null,'transparent',md5('123456'),'13901234561',default,default,default),
(null,'hume24',md5('123456'),'13901234561',default,default,default),
(null,'simple',md5('123456'),'13901234561',default,default,default),
(null,'d3stiny',md5('123456'),'13901234561',default,default,default),
(null,'dangerou',md5('123456'),'13901234561',default,default,default),
(null,'bryan',md5('123456'),'13901234561',default,default,default),
(null,'hunter',md5('123456'),'13901234561',default,default,default),
(null,'cameron',md5('123456'),'13901234561',default,default,default),
(null,'zachary',md5('123456'),'13901234561',default,default,default),
(null,'austin',md5('123456'),'13901234561',default,default,default),
(null,'blake',md5('123456'),'13901234561',default,default,default),
(null,'oliver',md5('123456'),'13901234561',default,default,default),
(null,'aidan',md5('123456'),'13901234561',default,default,default),
(null,'hayden',md5('123456'),'13901234561',default,default,default),
(null,'thomas',md5('123456'),'13901234561',default,default,default),
(null,'charles',md5('123456'),'13901234561',default,default,default),
(null,'carlos',md5('123456'),'13901234561',default,default,default),
(null,'antonio',md5('123456'),'13901234561',default,default,default),
(null,'harlean',md5('123456'),'13901234561',default,default,default),
(null,'Lgnorant',md5('123456'),'13901234561',default,default,default),
(null,'manipula',md5('123456'),'13901234561',default,default,default),
(null,'frIendshIp',md5('123456'),'13901234561',default,default,default),
(null,'domineering',md5('123456'),'13901234561',default,default,default),
(null,'alone',md5('123456'),'13901234561',default,default,default),
(null,'madness',md5('123456'),'13901234561',default,default,default),
(null,'presumptus',md5('123456'),'13901234561',default,default,default),
(null,'grieved',md5('123456'),'13901234561',default,default,default),
(null,'Trace',md5('123456'),'13901234561',default,default,default),
(null,'dissolute',md5('123456'),'13901234561',default,default,default),
(null,'Rodman',md5('123456'),'13901234561',default,default,default),
(null,'Nostalgia',md5('123456'),'13901234561',default,default,default),
(null,'Anesthesia',md5('123456'),'13901234561',default,default,default),
(null,'Ecstasy',md5('123456'),'13901234561',default,default,default),
(null,'Featmellow',md5('123456'),'13901234561',default,default,default),
(null,'Eternal',md5('123456'),'13901234561',default,default,default),
(null,'Toxicant',md5('123456'),'13901234561',default,default,default),
(null,'Adalyn',md5('123456'),'13901234561',default,default,default),
(null,'Ainsley',md5('123456'),'13901234561',default,default,default),
(null,'aryony',md5('123456'),'13901234561',default,default,default),
(null,'eleanora',md5('123456'),'13901234561',default,default,default),
(null,'emerson',md5('123456'),'13901234561',default,default,default),
(null,'estelle',md5('123456'),'13901234561',default,default,default),
(null,'jocelyn',md5('123456'),'13901234561',default,default,default),
(null,'liliana',md5('123456'),'13901234561',default,default,default),
(null,'meilani',md5('123456'),'13901234561',default,default,default),
(null,'judith',md5('123456'),'13901234561',default,default,default),
(null,'Norah',md5('123456'),'13901234561',default,default,default),
(null,'pandora',md5('123456'),'13901234561',default,default,default),
(null,'primrose',md5('123456'),'13901234561',default,default,default),
(null,'Alivia',md5('123456'),'13901234561',default,default,default),
(null,'Tallulah',md5('123456'),'13901234561',default,default,default),
(null,'Polly',md5('123456'),'13901234561',default,default,default),
(null,'Robbie',md5('123456'),'13901234561',default,default,default),
(null,'Willie',md5('123456'),'13901234561',default,default,default),
(null,'Lcott',md5('123456'),'13901234561',default,default,default),
(null,'Leroy',md5('123456'),'13901234561',default,default,default),
(null,'Jermaine',md5('123456'),'13901234561',default,default,default),
(null,'Darnell',md5('123456'),'13901234561',default,default,default),
(null,'Penelope',md5('123456'),'13901234561',default,default,default),
(null,'Stella',md5('123456'),'13901234561',default,default,default),
(null,'Bernard',md5('123456'),'13901234561',default,default,default),
(null,'Kurtis',md5('123456'),'13901234561',default,default,default);

#2 首页轮播表 mc_index_carousel
CREATE TABLE mc_index_carousel(
	bid INT PRIMARY KEY AUTO_INCREMENT,
	bpic VARCHAR(128)
);

INSERT INTO mc_index_carousel VALUES
(null,'Images/index/banner_01.jpg'),
(null,'Images/index/banner_02.jpg'),
(null,'Images/index/banner_03.jpg');

#3 商品分类表 mc_cake_sort
CREATE TABLE mc_cake_sort(
	mc_sort_id INT PRIMARY KEY AUTO_INCREMENT,
	mc_sort_name VARCHAR(16)
);

INSERT INTO mc_cake_sort VALUES
(null,'拿破仑'),
(null,'鲜奶'),
(null,'慕斯'),
(null,'芝士'),
(null,'巧克力'),
(null,'咖啡'),
(null,'坚果'),
(null,'水果'),
(null,'冰淇淋'),
(null,'小食');

#4 商品热度表 mc_cake_hot
CREATE TABLE mc_cake_hot(
	mc_hot_id INT PRIMARY KEY AUTO_INCREMENT,
	mc_hot_name VARCHAR(32),
	mc_hot_pic VARCHAR(128) DEFAULT ''
);

INSERT INTO mc_cake_hot VALUES
(null,'新品','Images/index/new.png'),
(null,'热销','Images/index/hot.png'),
(null,'金牌','Images/index/gold.png'),
(null,'普通',default);

#5 商品规格表 mc_cake_spec
CREATE TABLE mc_cake_spec(
    spec_id INT PRIMARY KEY AUTO_INCREMENT,
    spec_name VARCHAR(32),               #规格名
    spec_num VARCHAR(16),                #适合人数
    spec_size VARCHAR(16)                #蛋糕大小
);

INSERT INTO mc_cake_spec VALUES
(null,'标准款','4-7','17*4.5cm'),
(null,'1磅','2-3人','16cm*10cm*5cm'),
(null,'2磅','4-7','23cm*14cm*5cm'),
(null,'3磅','8-12','28cm*18cm*5cm'),
(null,'5磅','12-20','36cm*22cm*5.5cm'),
(null,'1.5磅','2-3','16cm*5cm'),
(null,'2.5磅','4-7','21cm*5.5cm');

#6 商品信息表 mc_cake_info
CREATE TABLE mc_cake_info(
	pid INT PRIMARY KEY AUTO_INCREMENT,
	mc_sort_id INT,					  #商品分类(口味)
	mc_hot_id INT DEFAULT 2,          #商品热度:新品--1,热销--2,金牌--3,普通--4(默认)
	mc_pic VARCHAR(128),              #商品图片
	eTitle VARCHAR(32),               #英文标题
	cTitle VARCHAR(32),               #中文标题
    eNote VARCHAR(512),               #主图下的英文
    cNote VARCHAR(512),               #主图下的中文
    smallPic VARCHAR(128),            #小图      #[]
    middlePic VARCHAR(512),           #中图      #[]详情页主图
    BigPic VARCHAR(512),              #大图      #[]
    material VARCHAR(64),             #原材料    #法国奶油..
    texture VARCHAR(32),              #口感      #绵软细腻
    flavor VARCHAR(32),               #口味      #芝士/奶油/酸乳
    flavor_base VARCHAR(32),          #口味基底  #Whipping Cream
    detailETitle VARCHAR(512),        #英文详情title
    detailCTitle VARCHAR(512),        #中文详情title
    detailImg VARCHAR(128),           #详情小图
    sImg VARCHAR(128)                 #俯瞰图
);

INSERT INTO mc_cake_info VALUES
(null,1,default,'Images/proInfo/1_1.jpg','Carré Blanc','简','La célèbre pâte feuilletée, les myrtilles bien sélectionnées, la génoise au fromage fondante,Voilà notre Carré Blanc pour les horoscopes de la vierge. C’est la perfection !','法国国宝级拿破仑酥皮、精心挑选的野生蓝莓、口感绝佳的轻乳芝士，献给极致挑剔的处女座。外表极致简洁，内心醇厚酥脆。必须美味，必须完美！','[Images/proInfo/1_1_small_01.jpg,Images/proInfo/1_1_small_02.jpg,Images/proInfo/1_1_small_03.jpg]','[Images/proInfo/1_1_middle_01.jpg,Images/proInfo/1_1_middle_02.jpg,Images/proInfo/1_1_middle_03.jpg]','[Images/proInfo/1_1_big_01.jpg,Images/proInfo/1_1_big_02.jpg,Images/proInfo/1_1_big_03.jpg]','法国奶油/法国黄油/世界臻选蓝莓/比利时白巧克力/新西兰奶油奶酪','酥脆浓郁','奶油/水果/芝士','Mousse','Pour les gens de l’horoscope de la Vierge, est-ce qu’il existe un gâteau parfait ? Voici notre solution, sur une surface bien plate blanche, les décorations parfaitement régulier, une présentation impeccable qui a une origine de Napoléon Myrtille.','处女座大脑里有没有完美的蛋糕？也许只有在纯白基底上将所有的食材按照规格一致、排列对齐、距离相同的方式，做成一款异常工整的蛋糕，才能让处女座也无可挑剔。','Images/proInfo/1_1_detail_small.png','Images/proInfo/1_1_detail_middle.jpg'),
(null,1,3,'Images/proInfo/1_2.jpg','Napoléon aux myrtilles','蓝莓轻乳拿破仑','Myrtilles fraiches, bio, feuilletage au goût de beurre frais, marmelade de myrtilles, crème chantilly, et tout celà dans le plaisir du palais .','精选野生蓝莓的清爽可口/芝士的香浓/优质奶油的醇厚 起酥皮的香脆可口/内层轻乳芝士的松软 层层美味/回味无穷','[Images/proInfo/1_2_small_01.jpg,Images/proInfo/1_2_small_02.jpg,Images/proInfo/1_2_small_03.jpg]','[Images/proInfo/1_2_middle_01.jpg,Images/proInfo/1_2_middle_02.jpg,Images/proInfo/1_2_middle_03.jpg]','[Images/proInfo/1_2_big_01.jpg,Images/proInfo/1_2_big_02.jpg,Images/proInfo/1_2_big_03.jpg]','法国奶油/法国黄油/世界臻选蓝莓/新西兰奶油奶酪/臻选白砂糖','酥脆浓郁','水果/芝士','Whipping Cream','Le prestigieux Napoléon, le gâteau de fromage allégé spécialement préparé, la crème française douce et les myrtilles importées sélectionnées présente ensemble un goût français inoubliable. ','作为法国国宝的拿破仑酥皮，精心调配的轻乳蛋糕，香甜的法国淡奶油以及精选进口新鲜蓝莓果，碰撞出让人品尝过就无法忘记的法国味道。','Images/proInfo/1_2_detail_small.png','Images/proInfo/1_2_detail_middle.jpg'),
(null,1,default,'Images/proInfo/1_3.jpg','Napoléon aux myrtilles','经典香草拿破仑','Avec un style typiquement français, ce gâteau unique vous laissera des souvenirs Napoléoniens.','纯正的法国风味/香浓绵甜的吉士酱 加上香脆起酥皮 入口即化/层层美味','[Images/proInfo/1_3_small_01.jpg,Images/proInfo/1_3_small_02.jpg,Images/proInfo/1_3_small_03.jpg]','[Images/proInfo/1_3_middle_01.jpg,Images/proInfo/1_3_middle_02.jpg,Images/proInfo/1_3_middle_03.jpg]','[Images/proInfo/1_3_big_01.jpg,Images/proInfo/1_3_big_02.jpg,Images/proInfo/1_3_big_03.jpg]','法国奶油/法国黄油/新西兰黄油/臻选白砂糖/马达加斯加香草棒','酥脆浓郁','芝士','whipping Cream /Pasty ','La pâte feuilletée croquante, avec la génoise moelleuse, elles se mettent en harmonie.','经典拿破仑酥皮搭配绵软蛋糕体，酥脆与柔滑的碰撞就仿佛巴黎街头的邂逅，惊艳且浪漫。','Images/proInfo/1_3_detail_small.png','Images/proInfo/1_3_detail_middle.jpg'),
(null,1,default,'Images/proInfo/1_4.jpg','Napoléon 1893','拿破仑1893','Depuis sa création en 1893 le restaurant Maxim, en plus de signes ne sont pas remplacés, il ce gâteau.','自1893年马克西姆餐厅成立以来，没换过的除了招牌，还有这款蛋糕。','[Images/proInfo/1_4_small_01.jpg,Images/proInfo/1_4_small_02.jpg,Images/proInfo/1_4_small_03.jpg]','[Images/proInfo/1_4_middle_01.jpg,Images/proInfo/1_4_middle_02.jpg,Images/proInfo/1_4_middle_03.jpg]','[Images/proInfo/1_4_big_01.jpg,Images/proInfo/1_4_big_02.jpg,Images/proInfo/1_4_big_03.jpg]','法国黄油/比利时牛奶巧克力/马达加斯加香草/美国巴旦木仁/新西兰黄油/臻选白砂糖','酥脆浓郁','巧克力/干果','Custard Cream','Millefeuille vanille, grande tradition dans la pâtisserie française, une image de l’histoire gastronomique française. ','黄油香草卡仕达酱，只有在法国才能吃到的味道，连同千层酥皮一口咬下去，味蕾舌尖上的恢弘乐章。','Images/proInfo/1_4_detail_small.png','Images/proInfo/1_4_detail_middle.jpg'),
(null,1,default,'Images/proInfo/1_5.jpg','La Forêt noir','黑森林拿破仑','La rencontre des fameuses pâtisseries : la forêt noir et les mille-feuilles, est un choque au niveaux goût en tant que texture, l`amertume douce de chocolat avec la croquante feuilletage, crémeux et fruité, parfumé au kirsch, une pure sensation de voyage à l`esprit au de là du pays du nord.','久负盛名的黑森林蛋糕遇上绝对经典的拿破仑酥皮，微苦与松脆，浓香丰满。融合樱桃的清爽、奶油的甜，带思绪飘往北地黑森林。','[Images/proInfo/1_5_small_01.jpg,Images/proInfo/1_5_small_02.jpg,Images/proInfo/1_5_small_03.jpg]','[Images/proInfo/1_5_middle_01.jpg,Images/proInfo/1_5_middle_02.jpg,Images/proInfo/1_5_middle_03.jpg]','[Images/proInfo/1_5_big_01.jpg,Images/proInfo/1_5_big_02.jpg,Images/proInfo/1_5_big_03.jpg]','法国奶油/比利时黑巧克力/臻选白砂糖/法国黄油/法国君度力娇酒','酥脆浓郁','巧克力','Whipping Cream','La forêt noir, originaire allemand. Nous gardons toujours sa combinaison de recette, décorée en pièce chocolat, a justement donné en forme rectangle.','起源于德国的黑森林蛋糕，不改变它的经典樱桃可可搭配，只在形状上调整为硬朗的长方形，并延续了传统的纯黑巧克力装饰.','Images/proInfo/1_5_detail_small.png','Images/proInfo/1_5_detail_middle.jpg');

INSERT INTO mc_cake_info VALUES
(null,2,default,'Images/proInfo/2_1.jpg','Tarte au durian','榴莲雪塔','S’il exist un goût, qui peut vous faire bouger, Il doit être le roi des fruits "Durian". Mélanger de la crème fraiche et plus que 45% de chair de durian Monthong Thailandais, une fois vous l’avez côuté , vous comprendrez notre sincérité.','若有一种味道，能让你闻香而欲动，必是果中之王“榴莲“，淡奶油与占比45%以上的泰国金枕榴莲肉厮磨出的醇厚香甜，一旦亲口尝过，便会懂我们的诚意。','[Images/proInfo/2_1_small_01.jpg,Images/proInfo/2_1_small_02.jpg,Images/proInfo/2_1_small_03.jpg]','[Images/proInfo/2_1_middle_01.jpg,Images/proInfo/2_1_middle_02.jpg,Images/proInfo/2_1_middle_03.jpg]','[Images/proInfo/2_1_big_01.jpg,Images/proInfo/2_1_big_02.jpg,Images/proInfo/2_1_big_03.jpg]','新西兰黄油/臻选白砂糖/马达加斯加香草棒/泰国榴莲','绵软细腻','奶油/水果','Whipping Cream','Mélange les crêpes et le chair de durian est un grand classique, un durian monthong même en Thaïlande est en forte demande. Grand morceaux de durian dans la bouche, le goût riche de long, accompagné de gâteau mousseline douce, décoré avec une couche de sucre en poudre, qui se tombent comment les flocons de neige.','可丽饼与榴莲肉的搭配堪称经典，而软绵香浓的自然熟成金枕榴莲，就算在泰国当地也是抢手货。大块榴莲肉入口，浓郁悠长，伴着松软的戚风蛋糕齿唇留香，轻饰一层糖粉，若蝉翼般飘落。','Images/proInfo/2_1_detail_small.png','Images/proInfo/2_1_detail_middle.jpg'),
(null,2,default,'Images/proInfo/2_2.jpg','Velour rouge','蔓越莓红丝绒','Dans la couleur de la paix et la confusion, la canneberge de haute qualité honore le parfum aristrocratique de l`histoire. MCAKE','完美的复苏红丝绒蛋糕的传统和历史/ 并选用新鲜蔓越莓点缀其上/ 让贵族般的色香/再度氤氲美妙的午后','[Images/proInfo/2_2_small_01.jpg,Images/proInfo/2_2_small_02.jpg,Images/proInfo/2_2_small_03.jpg]','[Images/proInfo/2_2_middle_01.jpg,Images/proInfo/2_2_middle_02.jpg,Images/proInfo/2_2_middle_03.jpg]','[Images/proInfo/2_2_big_01.jpg,Images/proInfo/2_2_big_02.jpg,Images/proInfo/2_2_big_03.jpg]','法国奶油/法国可可粉/美国蔓越莓/新西兰奶油奶酪/臻选白砂糖','绵软细腻','芝士','whipping Cream /Pasty Cream','Gâteau célèbre créé chez Waldolf de New York,jamais absent aux tapis rouges des grands événements.','原产自纽约华尔道夫的名品，每逢明星走红毯必会出现的角色。','Images/proInfo/2_2_detail_small.png','Images/proInfo/2_2_detail_middle.jpg'),
(null,2,4,'Images/proInfo/2_3.jpg','Napoléon vanille','经典香草拿破仑','Avec un style typiquement français, ce gâteau unique vous laissera des souvenirs Napoléoniens.','纯正的法国风味/香浓绵甜的吉士酱 加上香脆起酥皮 入口即化/层层美味','[Images/proInfo/2_3_small_01.jpg,Images/proInfo/2_3_small_02.jpg,Images/proInfo/2_3_small_03.jpg]','[Images/proInfo/2_3_middle_01.jpg,Images/proInfo/2_3_middle_02.jpg,Images/proInfo/2_3_middle_03.jpg]','[Images/proInfo/2_3_big_01.jpg,Images/proInfo/2_3_big_02.jpg,Images/proInfo/2_3_big_03.jpg]','法国奶油/法国黄油/新西兰黄油/臻选白砂糖/马达加斯加香草棒','酥脆浓郁','芝士','whipping Cream /Pasty Cream','','','',''),
(null,2,4,'Images/proInfo/2_4.jpg','Fraise-Chantilly','鲜莓印雪','Soleil après les chutes de neige, prenant une profonde inspiration, se sentir la douceur de la crème. Les rouges、mûres fraises，comme les elfes, tombant sur la terre.','雪过天晴后的第一口呼吸，甜蜜清新得不落俗套，鲜红的草莓，如俏皮的精灵降落凡间。','[Images/proInfo/2_4_small_01.jpg,Images/proInfo/2_4_small_02.jpg,Images/proInfo/2_4_small_03.jpg]','[Images/proInfo/2_4_middle_01.jpg,Images/proInfo/2_4_middle_02.jpg,Images/proInfo/2_4_middle_03.jpg]','[Images/proInfo/2_4_big_01.jpg,Images/proInfo/2_4_big_02.jpg,Images/proInfo/2_4_big_03.jpg]','法国奶油/比利时黑巧克力/法国君度力娇酒/新西兰黄油/臻选白砂糖/臻选草莓/世界臻选蓝莓果','绵软细腻','奶油/水果','Whipping Cream','Faire une promenade dans le jardin après la première neige, prendre une bouchée de fraises fraîches, moelleuse crème Cointreau, c`est le goût de Paris en hiver.','初雪过后漫步在杜乐丽花园的小道上，从圣诞集市上买到的有机草莓在口中化开，这就是冬天巴黎的味道。','Images/proInfo/2_4_detail_small.png','Images/proInfo/2_4_detail_middle.jpg'),
(null,2,4,'Images/proInfo/2_5.jpg','Gâteau de crêpes','法香奶油可丽','Une genoise légère, des crêpes fondantes, un goût subtile de crème de fromage, et une domination d’amandes torrifiées.','奶油绵甜柔软、香郁醇滑/轻乳芝士蛋糕松软可口/ 弹性十足的可丽饼/细腻浓郁的芝士酱/以及松脆的巴旦木仁片/ 口感层次极为丰富','[Images/proInfo/2_5_small_01.jpg,Images/proInfo/2_5_small_02.jpg,Images/proInfo/2_5_small_03.jpg]','[Images/proInfo/2_5_middle_01.jpg,Images/proInfo/2_5_middle_02.jpg,Images/proInfo/2_5_middle_03.jpg]','[Images/proInfo/2_5_big_01.jpg,Images/proInfo/2_5_big_02.jpg,Images/proInfo/2_5_big_03.jpg]','法国奶油/美国巴旦木仁/爱尔兰百利甜酒/新西兰黄油/新西兰奶油奶酪/臻选白砂糖','绵软细腻','芝士','Whipping Cream','Gâteau de crêpes à la crème La crêpe est un dessert français traditionnel très populaire. Nous faisons ici un gâteau innové de la crêpe pour vous montrer un délice du bonheur.','可丽饼是款传统的法式甜品，倍受欢迎，我们把它进化在蛋糕中，给你一种幸福的美味。','Images/proInfo/2_5_detail_small.png','Images/proInfo/2_5_detail_middle.jpg'),
(null,2,2,'Images/proInfo/2_6.jpg','Napoléon aux myrtilles','蓝莓轻乳拿破仑','Myrtilles fraiches, bio, feuilletage au goût de beurre frais, marmelade de myrtilles, crème chantilly, et tout celà dans le plaisir du palais .','精选野生蓝莓的清爽可口/芝士的香浓/优质奶油的醇厚 起酥皮的香脆可口/内层轻乳芝士的松软 层层美味/回味无穷','[Images/proInfo/2_6_small_01.jpg,Images/proInfo/2_6_small_02.jpg,Images/proInfo/2_6_small_03.jpg]','[Images/proInfo/2_6_middle_01.jpg,Images/proInfo/2_6_middle_02.jpg,Images/proInfo/2_6_middle_03.jpg]','[Images/proInfo/2_6_big_01.jpg,Images/proInfo/2_6_big_02.jpg,Images/proInfo/2_6_big_03.jpg]','法国奶油/法国黄油/世界臻选蓝莓/新西兰奶油奶酪/臻选白砂糖','酥脆浓郁','水果/芝士','Whipping Cream','Le prestigieux Napoléon, le gâteau de fromage allégé spécialement préparé, la crème française douce et les myrtilles importées sélectionnées présente ensemble un goût français inoubliable. ','作为法国国宝的拿破仑酥皮，精心调配的轻乳蛋糕，香甜的法国淡奶油以及精选进口新鲜蓝莓果，碰撞出让人品尝过就无法忘记的法国味道。','Images/proInfo/2_6_detail_small.png','Images/proInfo/2_6_detail_middle.jpg'),
(null,2,2,'Images/proInfo/2_7.jpg','Jardin d`Alice','爱丽丝花境','Framboise aigre, Lychee sucrée, s’éclatait étincelles de l’amour sur la langue, Comme l’humeur de la jeune fille qui se détours innombrable, qui est rafraîchissant .','树莓的酸，荔枝的甜，在舌尖上碰撞出恋爱的火花，犹如少女心境的千回百转，沁人心脾。','[Images/proInfo/2_7_small_01.jpg,Images/proInfo/2_7_small_02.jpg,Images/proInfo/2_7_small_03.jpg]','[Images/proInfo/2_7_middle_01.jpg,Images/proInfo/2_7_middle_02.jpg,Images/proInfo/2_7_middle_03.jpg]','[Images/proInfo/2_7_big_01.jpg,Images/proInfo/2_7_big_02.jpg,Images/proInfo/2_7_big_03.jpg]','法国奶油/臻选白砂糖/法国果茸','入口即化','奶油/树莓/荔枝','Whipping Cream','J’aimerais t’offrir un rêve d’amour, une jeune fille marche dans un cheminée , traverse un village fleurissant, tu me regardes avec tes yeux souriants, s’ennuie jamais .','我想送给你们一个关于爱情的梦境，梦境里是少女行走在小镇花径的身影，回眸笑眼弯弯，一生不厌。','Images/proInfo/2_7_detail_small.png','Images/proInfo/2_7_detail_middle.jpg'),
(null,2,4,'Images/proInfo/2_8.jpg','Genoise café','卡法香缇','Traditionel et unique, l`amertume du café et de la crème vous conduisent dans un rêve de romantisme et d`amour. MCAKE/','传承独特技艺的奶油咖啡香缇蛋糕/融入更多浪漫味道/ 等待你用心揭开','[Images/proInfo/2_8_small_01.jpg,Images/proInfo/2_8_small_02.jpg,Images/proInfo/2_8_small_03.jpg]','[Images/proInfo/2_8_middle_01.jpg,Images/proInfo/2_8_middle_02.jpg,Images/proInfo/2_8_middle_03.jpg]','[Images/proInfo/2_8_big_01.jpg,Images/proInfo/2_8_big_02.jpg,Images/proInfo/2_8_big_03.jpg]','法国奶油/比利时黑巧克力/意大利加利安奴酒/也门咖啡/法国可可粉/新西兰奶油奶酪/臻选白砂糖','绵软细腻','咖啡/巧克力/芝士','Whipping Cream /Mousse','La chantilly désigne une crème fouettée parfumée. Le goût du café de ce gâteau met en valeur encore mieux sa fraîcheur aromatisée et vous donne un arrière-goût persistant. ','“香缇”是指奶油经过调配使它口味清香，这款产品结合了咖啡口味，就更能突出它的清香口感，令人回味','Images/proInfo/2_8_detail_small.png','Images/proInfo/2_8_detail_middle.jpg'),
(null,2,4,'Images/proInfo/2_9.jpg','Soirée Bailay’s','百利派对','Un moment merveilleux entre les amis, les amoureux et les soirées Mélange la crème et Bailay’s, rajouté un cout fine du chocolat blanc du Bruxelle Partagé une dégustation conviviale et fantastique','来一场百利私享派对 奶油和威士忌的美妙融合，再加一点比利时白巧克力 感受着丝般顺滑的口感，分享与闺蜜专属的时间','[Images/proInfo/2_9_small_01.jpg,Images/proInfo/2_9_small_02.jpg,Images/proInfo/2_9_small_03.jpg]','[Images/proInfo/2_9_middle_01.jpg,Images/proInfo/2_9_middle_02.jpg,Images/proInfo/2_9_middle_03.jpg]','[Images/proInfo/2_9_big_01.jpg,Images/proInfo/2_9_big_02.jpg,Images/proInfo/2_9_big_03.jpg]','法国奶油/爱尔兰百利甜酒/臻选白砂糖/比利时白巧克力','绵软细腻','奶油/巧克力','Whipping Cream','Avec l’apparence de la plus grande simplicité,le dessert Baileys est la meilleure interprétationde l’aspiration des jeunes filles vers l’amour. ','外型极致简约，少女对于恋爱憧憬，百利甜是完美的诠释。','Images/proInfo/2_9_detail_small.png','Images/proInfo/2_9_detail_middle.jpg'),
(null,2,4,'Images/proInfo/2_10.jpg','Mangue chantilly','芒果•Mangue','La meilleure qualitée de mangue que l` on puisse trouver L ‘additon de mangue et de fruit de la passion pour une saveur parfaite Un parfum qui ne pourra que exalter vos papilles','用心甄选热带优质芒果/ 芒果及百香果的完美组合/ 香气迷人，绽放清甜芳华','[Images/proInfo/2_10_small_01.jpg,Images/proInfo/2_10_small_02.jpg,Images/proInfo/2_10_small_03.jpg]','[Images/proInfo/2_10_middle_01.jpg,Images/proInfo/2_10_middle_02.jpg,Images/proInfo/2_10_middle_03.jpg]','[Images/proInfo/2_10_big_01.jpg,Images/proInfo/2_10_big_02.jpg,Images/proInfo/2_10_big_03.jpg]','法国奶油/世界臻选芒果/法国百香果果茸/法国芒果果茸/美国柠檬/新西兰黄油/臻选白砂糖','绵软细腻','水果','Whipping Cream','Cœur à la mangueLa gelée est une image classique dans notre mémoire de l’enfance.On la rappelle avec le goût frais de la mangueet une couche de gâteau très souple.','果冻是我们儿时的记忆，用清爽的芒果味将它重现，配以松软的白胚','Images/proInfo/2_10_detail_small.png','Images/proInfo/2_10_detail_middle.jpg'),
(null,2,4,'Images/proInfo/2_11.jpg','Gâteau des anges','天使巧克力','D`un goût de plus de 100 ans, un gâteau frabriqué d`une façon minutieusevous rappelle l`inoccupation et le romantisme parisiens. MCAKE/','用巴黎的慵懒与浪漫/与马克西姆传承的百年味道/ 精心制作出让天使都会爱上的美丽','[Images/proInfo/2_11_small_01.jpg,Images/proInfo/2_11_small_02.jpg,Images/proInfo/2_11_small_03.jpg]','[Images/proInfo/2_11_middle_01.jpg,Images/proInfo/2_11_middle_02.jpg,Images/proInfo/2_11_middle_03.jpg]','[Images/proInfo/2_11_big_01.jpg,Images/proInfo/2_11_big_02.jpg,Images/proInfo/2_11_big_03.jpg]','法国奶油/比利时黑巧克力/法国可可粉/臻选白砂糖','绵软细腻','巧克力','Butter Cream/Pasty Cream','Le mariage parfait du chocolat et de la crème.Avec un goût qui plaît au tout le monde, il a une élégance de la douceur des nuages.','巧克力与奶油口味的完美融合，针对大众口味调配，体现柔美的云朵样感觉。','Images/proInfo/2_11_detail_small.png','Images/proInfo/2_11_detail_middle.jpg');

INSERT INTO mc_cake_info VALUES
(null,3,4,'Images/proInfo/3_1.jpg','Pink Rosette','Pink•罗赛特','Une crème légère au chocolat blanc parfumée à la rose, litchis frais coupés en cubes, une fine gelée de framboise. Le Pink Rosette vous offrirait une expérience','细腻软甜的玫瑰白巧克力慕斯邂逅酸爽的树莓啫喱于珍馐荔枝 色与味的双重盛宴','[Images/proInfo/3_1_small_01.jpg,Images/proInfo/3_1_small_02.jpg,Images/proInfo/3_1_small_03.jpg]','[Images/proInfo/3_1_middle_01.jpg,Images/proInfo/3_1_middle_02.jpg,Images/proInfo/3_1_middle_03.jpg]','[Images/proInfo/3_1_big_01.jpg,Images/proInfo/3_1_big_02.jpg,Images/proInfo/3_1_big_03.jpg]','法国奶油/新西兰黄油/臻选白砂糖/法国果茸/臻选荔枝/云南玫瑰汁/比利时白巧克力','入口即化','水果','Mousse','Un bouquet de roses et une branche de litchis au début de l’été, c’est le romantisme de Paris. Le chocolat en rose est la belle rencontre de ces deux.','初夏的巴黎，一束玫瑰和一串新鲜饱满的荔枝，这就是法国特有的浪漫气息，粉色的巧克力将二者完美地聚合。','Images/proInfo/3_1_detail_small.png','Images/proInfo/3_1_detail_middle.jpg'),
(null,3,2,'Images/proInfo/3_2.jpg','Nino','尼诺','A ce moment,laissez votre langue dominent votre joie.un parfum délicat de la crème cheese se cache sous les couches moelleux, qui refuse se fondre sauf dans la bouche.','这一刻，让舌尖主宰你的私享。蓬松夹着鲜香淡雅，只融在口的浓浓芝香，填满心的另一半。','[Images/proInfo/3_2_small_01.jpg,Images/proInfo/3_2_small_02.jpg,Images/proInfo/3_2_small_03.jpg,Images/proInfo/3_2_small_04.jpg]','[Images/proInfo/3_2_middle_01.jpg,Images/proInfo/3_2_middle_02.jpg,Images/proInfo/3_2_middle_03.jpg,Images/proInfo/3_2_middle_04.jpg]','[Images/proInfo/3_2_big_01.jpg,Images/proInfo/3_2_big_02.jpg,Images/proInfo/3_2_big_03.jpg,Images/proInfo/3_2_big_04.jpg]','法国奶油/新西兰黄油/臻选白砂糖/新西兰奶油奶酪','入口即化','芝士','Cheese','Quelle est l`expression du visage de votre humeur? Doux Nino vous accompagner, une innocence enfantine.','什么表情对你此刻心情？爱笑爱闹，暖心尼诺陪伴你，童心依旧。','Images/proInfo/3_2_detail_small.png','Images/proInfo/3_2_detail_middle.jpg'),
(null,3,4,'Images/proInfo/3_3.jpg','Carré Blanc','简','La célèbre pâte feuilletée, les myrtilles bien sélectionnées, la génoise au fromage fondante,Voilà notre Carré Blanc pour les horoscopes de la vierge. C’est la perfection !','法国国宝级拿破仑酥皮、精心挑选的野生蓝莓、口感绝佳的轻乳芝士，献给极致挑剔的处女座。外表极致简洁，内心醇厚酥脆。必须美味，必须完美！','[Images/proInfo/3_3_small_01.jpg,Images/proInfo/3_3_small_02.jpg,Images/proInfo/3_3_small_03.jpg]','[Images/proInfo/3_3_middle_01.jpg,Images/proInfo/3_3_middle_02.jpg,Images/proInfo/3_3_middle_03.jpg]','[Images/proInfo/3_3_big_01.jpg,Images/proInfo/3_3_big_02.jpg,Images/proInfo/3_3_big_03.jpg]','法国奶油/法国黄油/世界臻选蓝莓/比利时白巧克力/新西兰奶油奶酪','酥脆浓郁','奶油/水果/芝士','Mousse','Pour les gens de l’horoscope de la Vierge, est-ce qu’il existe un gâteau parfait ? Voici notre solution, sur une surface bien plate blanche, les décorations parfaitement régulier, une présentation impeccable qui a une origine de Napoléon Myrtille.','处女座大脑里有没有完美的蛋糕？也许只有在纯白基底上将所有的食材按照规格一致、排列对齐、距离相同的方式，做成一款异常工整的蛋糕，才能让处女座也无可挑剔。','Images/proInfo/3_3_detail_small.png','Images/proInfo/3_3_detail_middle.jpg'),
(null,3,4,'Images/proInfo/3_4.jpg','Sablé parfait','沙布蕾芭菲','Une recette tradionnelle française, avec une mousse à la vanille de Madagascar et un coulis au chocolat qui fond directement dans la bouche, le Parfait à la vanille vous donnerait le fraicheur en plein été.','法式传统沙布蕾饼，搭配马达加斯加香草芭菲和熔岩巧克力，入口即化，形成绝佳口感。','[Images/proInfo/3_4_small_01.jpg,Images/proInfo/3_4_small_02.jpg,Images/proInfo/3_4_small_03.jpg]','[Images/proInfo/3_4_middle_01.jpg,Images/proInfo/3_4_middle_02.jpg,Images/proInfo/3_4_middle_03.jpg]','[Images/proInfo/3_4_big_01.jpg,Images/proInfo/3_4_big_02.jpg,Images/proInfo/3_4_big_03.jpg]','法国奶油/法国可可粉/新西兰黄油/瑞士白巧克力/巧克力酱/马达加斯加香草棒/臻选白砂糖','入口即化','巧克力','Mousse','Le Parfait est sans aucun doute le meilleur choix pour l’été. Il chasse la chaleur avec la finesse et la fraîcheur de la mousse.','芭菲，源于法语Parfait音译。可可粉和香草以完美的比例搭配，保留慕斯的细腻和爽滑，尽享无穷回味。','Images/proInfo/3_4_detail_small.png','Images/proInfo/3_4_detail_middle.jpg'),
(null,3,4,'Images/proInfo/3_5.jpg','Le MOJITO','Mojito 柠•漾','Une mousse au citron vert légèrement aromatisée au rhum blanc, une gélée verte de menthe, le Mojito vous présente une harmonie entre l’acidité et la fraîcheur.','Mojito 柠•漾，柔滑慕斯内蕴Q弹酒冻，绝妙配比带来口感的平衡，不太浓烈也不过于寡淡，青柠独特的酸甜带出白朗姆酒的微醺之意。','[Images/proInfo/3_5_small_01.jpg,Images/proInfo/3_5_small_02.jpg,Images/proInfo/3_5_small_03.jpg]','[Images/proInfo/3_5_middle_01.jpg,Images/proInfo/3_5_middle_02.jpg,Images/proInfo/3_5_middle_03.jpg]','[Images/proInfo/3_5_big_01.jpg,Images/proInfo/3_5_big_02.jpg,Images/proInfo/3_5_big_03.jpg]','法国奶油/新西兰黄油/法国果茸/比利时白巧克力/马来西亚薄荷糖浆/世界臻选青柠檬/波多黎各朗姆酒/臻选薄荷叶/臻选白砂糖','入口即化','水果/巧克力','Mousse','Les menthes fraîches, les citrons verts et le rhum blanc, tous les ingrédients du cocktail Mojito sont dans ce gâteau, le MOJITO vous apportera le fraîcheur et le goût inoubliable, votre aventure avec ce cocktail mangeable commence. ','炎炎夏日，你是否渴望在沙滩的躺椅上享受一杯清凉的Mojito鸡尾酒呢？清凉的薄荷搭配酸爽的青柠，佐以纯正的白朗姆酒，为夏日带来无限清爽；“Mojito 柠•漾”不仅仅是一款蛋糕，更是一“杯”可以吃的Mojito','Images/proInfo/3_5_detail_small.png','Images/proInfo/3_5_detail_middle.jpg'),
(null,3,4,'Images/proInfo/3_6.jpg','Ricotta','瑞可塔厚爱','Même c’est un gâteau au fromage, il est différent que le gâteau au fromage velouté. Une combinaison parfaite du fromage grillé et fromage congelé. Seulement quand nous connaissons le ratio, le saveur plus profond du fromage peut être se réveiller.','同样是芝士蛋糕，却与「香溢新芝」大相径庭，烤芝士与冻芝士的完美结合，只有掌握精确配比，才能唤醒暗藏在芝士内部更深层次的味道。','[Images/proInfo/3_6_small_01.jpg,Images/proInfo/3_6_small_02.jpg,Images/proInfo/3_6_small_03.jpg]','[Images/proInfo/3_6_middle_01.jpg,Images/proInfo/3_6_middle_02.jpg,Images/proInfo/3_6_middle_03.jpg]','[Images/proInfo/3_6_big_01.jpg,Images/proInfo/3_6_big_02.jpg,Images/proInfo/3_6_big_03.jpg]','法国黄油/法国奶油/法国芝士/美国巴旦木仁/美国核桃','绵软细腻','芝士','Cheese','Seulement le patissier creative peut montrer deux différents saveurs avec des ingrédients presque le même . Le Ricotta contiens un saveur riche du fromage grillé et une fra?cheur du fromage congelé, à ce moment, profitez d`un fromage plus pur.','富有想象力的蛋糕师，才会用近乎相同的食材呈现迥异口味。烤芝士的浓郁与冻芝士的清新，雕琢一款别致无二的「瑞可塔厚爱」，这一刻，让芝士更纯粹。','Images/proInfo/3_6_detail_small.png','Images/proInfo/3_6_detail_middle.jpg'),
(null,3,4,'Images/proInfo/3_7.jpg','Fromage Velouté','香溢新芝','La décoration n’est plus indispensable. Une émulsion de la crème cheese, mixé d’une couche de la crème fouettée. Une saveur harmonieuse et pénétrante.','传承享受纯粹，修饰不再重要 只融在口的芝香，让舌尖主宰你的私享 蓬松夹着鲜香淡雅，因齿间的温度而融化肆溢 奶香轻盈，用层层的绵柔瞬间勾勒永恒的味觉记忆','[Images/proInfo/3_7_small_01.jpg,Images/proInfo/3_7_small_02.jpg,Images/proInfo/3_7_small_03.jpg]','[Images/proInfo/3_7_middle_01.jpg,Images/proInfo/3_7_middle_02.jpg,Images/proInfo/3_7_middle_03.jpg]','[Images/proInfo/3_7_big_01.jpg,Images/proInfo/3_7_big_02.jpg,Images/proInfo/3_7_big_03.jpg]','法国奶油/新西兰黄油/臻选白砂糖/新西兰奶油奶酪','入口即化','芝士','Cheese','C’est un gâteau de fromage innovant. Nous créons la rencontre du gâteau de fromage et de la mousse de fromage. Il apportera surement aux amateurs du fromage une nouvelle expérience.','这是一款创新的芝士蛋糕，把芝士蛋糕和芝士慕斯组合于一体，能带给喜爱芝士类甜品的朋友焕然一新的口感。','Images/proInfo/3_7_detail_small.png','Images/proInfo/3_7_detail_middle.jpg'),
(null,3,4,'Images/proInfo/3_8.jpg','Joséphine','约瑟芬玫瑰','Des rosettes pour les amoureux, une histoire d’amour, une romance unique de toute la vie.','见证无数情侣最甜蜜的一刻，从舌尖蔓延到心间的感动，今生今世唯一爱恋','[Images/proInfo/3_8_small_01.jpg,Images/proInfo/3_8_small_02.jpg,Images/proInfo/3_8_small_03.jpg]','[Images/proInfo/3_8_middle_01.jpg,Images/proInfo/3_8_middle_02.jpg,Images/proInfo/3_8_middle_03.jpg]','[Images/proInfo/3_8_big_01.jpg,Images/proInfo/3_8_big_02.jpg,Images/proInfo/3_8_big_03.jpg]','法国奶油/比利时黑巧克力/新西兰黄油/臻选白砂糖/马达加斯加香草棒/比利时白巧克力','入口即化','巧克力/慕斯','Mousse','Des rosettes pour les amoureux, une histoire d’amour, une romance unique de toute la vie. ','巧克力&玫瑰花，见证无数情侣最甜蜜的一刻，从舌尖蔓延到心间的感动，今生今世唯一爱恋 。','Images/proInfo/3_8_detail_small.png','Images/proInfo/3_8_detail_middle.jpg');


(null,3,商品热度,'商品图片','英文标题','中文标题','主图下的英文','主图下的中文','[]','[]','[]','原材料','口感','口味','口味基底','英文详情title','中文详情title','详情图片','俯瞰图'),
(null,3,商品热度,'商品图片','英文标题','中文标题','主图下的英文','主图下的中文','[]','[]','[]','原材料','口感','口味','口味基底','英文详情title','中文详情title','详情图片','俯瞰图'),
(null,3,商品热度,'商品图片','英文标题','中文标题','主图下的英文','主图下的中文','[]','[]','[]','原材料','口感','口味','口味基底','英文详情title','中文详情title','详情图片','俯瞰图'),
(null,3,商品热度,'商品图片','英文标题','中文标题','主图下的英文','主图下的中文','[]','[]','[]','原材料','口感','口味','口味基底','英文详情title','中文详情title','详情图片','俯瞰图'),


#(null,'#商品分类','#商品热度','商品图片','英文标题','中文标题','主图下的英文','主图下的中文','小图[]','中图[]','大图[]','原材料','口感','口味','口味基底','英文详情title','中文详情title','详情图片','俯瞰图')
#商品热度:新品--1,热销--2,金牌--3,普通--4(默认) default 2

#7 商品所属规格价钱
CREATE TABLE mc_cake_spec_price(
    pid INT,                             #商品id
    spec_id INT,             			 #商品规格id
    price VARCHAR(32),                   #价钱
    default_spec INT                     #0->不显示 1->显示()
);

INSERT INTO mc_cake_spec_price VALUES
(1,2,'218',0),
(1,3,'318',1),

(2,2,'198',0),
(2,3,'298',1),
(2,4,'428',0),
(2,5,'728',0),

(3,2,'198',0),
(3,3,'298',1),
(3,4,'428',0),
(3,5,'728',0),

(4,2,'198',0),
(4,3,'298',1),
(4,4,'428',0),
(4,5,'728',0),

(5,2,'198',0),
(5,3,'298',1),
(5,4,'428',0),
(5,5,'728',0),

#2

(6,2,'218',0),
(6,3,'318',1),
(6,4,'458',0),
(6,5,'750',0),

(7,2,'198',0),
(7,3,'298',1),
(7,4,'428',0),
(7,5,'728',0),

(8,2,'198',0),
(8,3,'298',1),
(8,4,'428',0),
(8,5,'728',0),

(9,2,'198',0),
(9,3,'298',1),
(9,4,'428',0),
(9,5,'728',0),

(10,2,'198',0),
(10,3,'298',1),
(10,4,'428',0),
(10,5,'728',0),

(11,2,'198',0),
(11,3,'298',1),
(11,4,'428',0),
(11,5,'728',0),

(12,6,'298',1),

(13,2,'198',0),
(13,3,'298',1),
(13,4,'428',0),
(13,5,'728',0),

(14,2,'198',0),
(14,3,'298',1),
(14,4,'428',0),
(14,5,'728',0),

(15,2,'198',0),
(15,3,'298',1),
(15,4,'428',0),
(15,5,'728',0),

(16,2,'198',0),
(16,3,'298',1),
(16,4,'428',0),
(16,5,'728',0),

#3

(17,2,'218',0),
(17,3,'318',1),
(17,4,'458',0),
(17,5,'750',0),

(18,1,'298',1),

(19,2,'218',0),
(19,3,'318',1),

(20,2,'218',0),
(20,3,'318',1),
(20,4,'458',0),
(20,5,'750',0),

(21,2,'198',0),
(21,3,'298',1),
(21,4,'428',0),

(22,2,'218',0),
(22,3,'318',1),
(22,4,'458',0),
(22,5,'750',0),

(23,2,'198',0),
(23,3,'298',1),
(23,4,'428',0),
(23,5,'728',0),

(24,3,'398',1);

#8 购物车表 mc_cart
CREATE TABLE mc_cart(
    cid INT PRIMARY KEY AUTO_INCREMENT,
    uid INT,
    pid INT,
    count INT,
    checked_spec INT,
    ischecked INT default 1   #0未选中 1已选中
);

INSERT INTO mc_cart VALUES
(null,1,1,1,2,0),
(null,1,1,2,3,1);

#9 订单表 mc_order #通过uid去用户表查询真实姓名,电话(,性别),通过pid去商品表查询具体哪个商品
CREATE TABLE mc_order(
    oid INT PRIMARY KEY AUTO_INCREMENT,
    uid INT,
    pid INT,
    count INT,
    order_time DATETIME,
    addr VARCHAR(256),
    pay INT,                  #付款方式 0-货到付款 1-支付宝 2-微信 3-银行卡 4-其他
    pay_state INT             #支付状态 0-已支付 1-未支付
);

#INSERT INTO mc_order VALUES();

#10 用户评价表 mc_comment
CREATE TABLE mc_comment(
    cid INT PRIMARY KEY AUTO_INCREMENT,  #评论id   null
    uid INT,                             #用户id   1-5
    pid INT,                             #商品id   1-24
    comment_title VARCHAR(64),           #标签
    comment_content VARCHAR(256),        #具体评论内容
    comment_time VARCHAR(256)            #评论时间  (具体时间待更改)
);
#ALTER TABLE mc_comment ADD comment_time VARCHAR(256) DEFAULT "2017-11-11";

INSERT INTO mc_comment VALUES
(null,1,1,'好吃','特别好吃'),
(null,2,2,'蛋糕很棒～','送货也很及时～性价比很高～就是感觉稍微甜了点儿～建议可以降低点甜度现在人都喜欢吃的清淡些健康些哈哈～总的来说还是很不错的体验～棒棒棒棒棒棒棒棒棒棒棒棒～下次可以试试看别的味道～会不会有没那么甜的～'),
(null,3,3,'味道确实不错','家人都说好吃，味道确实不错。但不能吃多，蛋糕吃多了都会腻的。'),
(null,4,4,'味道不错','还可以，3个人吃还吃不了，已经最小的了，味道不错，也不是特别甜的，水果有的好酸。'),
(null,5,5,'很好吃','很好吃，但总体还是很满意的，棒棒哒，还会继续关注的……'),
(null,6,6,'超满意，蛋糕非常新鲜','超满意，蛋糕非常新鲜，好吃也不贵，优惠完大概才50多，超值，家人喜欢，有活动一定会再来买的，很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,7,7,'蛋糕真心不错','蛋糕真心不错，朋友推荐购买的，太划算了，还会继续回购的'),
(null,8,8,'很好吃哟','很好吃哟，绵绵的，一磅大概有六寸那么大，非常够吃，最厉害是盘子和叉子都是硬的厚的塑料，非常高端。'),
(null,9,9,'女朋友收到可喜欢了','味道也好吃，还按我的要求写了女朋友生日'),
(null,10,10,'非常好吃','经过宿舍8个人的一致认同 非常好吃(??ω?)? 非常满意 我的两个室友生日可以说是很圆满了'),
(null,11,11,'蛋糕好吃','蛋糕好吃，吃太多会腻。6寸实际看起来好小好小好小个，不过我们三个人吃够够的了。'),
(null,12,12,'赞赞赞～蛋糕很绵软','比较轻口，不会那么腻～味的也可以，价格也合适～各种赞，包装也完美'),
(null,13,13,'味道真的很好吃','买的一磅，免费自动升级到1.5磅，看上去小小的，宿舍6个妹子都够吃。送货准时，给室友过生日的不二之选。'),
(null,14,14,'很满意','叉子盘子带标志显高档，味道不错，跟平常买的带蛋糕的不一样，全是乳酪，好吃，一份够6个人吃刚好，差不多了，再吃第二块会腻的'),
(null,15,15,'味道都很好','一次拍了两款，味道都很好，下次蛋糕继续光顾'),
(null,16,16,'很好','提前三周买的，到当天准点送到，很好，味道不错，同事们都赞不绝口'),
(null,17,17,'味道还不错，香浓','味道还不错，香浓，吃多了有点腻，送货前都打电话确定的，很好，又定了两个……'),
(null,18,18,'挺好的','挺好的，味道不错。'),
(null,19,19,'很好吃的蛋糕','很好吃的蛋糕，你值得拥有'),
(null,20,20,'蛋糕好好吃的！','室友都说好吃 而且分量足 刚打开的时候觉得不大 分起来分了十来个人 奶油很香而且不腻 真的好吃'),
(null,21,21,'超级好吃','超级负责。这个蛋糕真的超级好吃。还会回购。'),
(null,22,22,'很不错','一直买你们家的蛋糕的，很不错，很喜欢吃～'),
(null,23,23,'味道比较纯正 ','味道比较纯正 但是太甜了太甜了太甜了 重要的话说三遍 有点腻 如果没这么甜就好了'),
(null,24,24,'很满意的蛋糕','很满意的蛋糕 妈妈很喜欢 配送准时 赞一个哈'),
(null,25,1,'好吃','很好吃，同事们都很喜欢。'),
(null,26,2,'非常好吃','同事们都说很好吃，下次还来买。'),
(null,27,3,'好好吃','5个人分着吃刚刚好'),
(null,28,4,'非常喜欢','非常好吃而且奶油的话也非常的甜而不腻希望之后有折扣和活动会继续购买的'),
(null,29,5,'买了三次了','好吃的 送的也特别早'),
(null,30,6,'喜欢','孩子很喜欢。早饭有着落了'),
(null,31,7,'挺好的','送的挺快的，蛋糕看起来也不错'),
(null,32,8,'很满意！','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,33,9,'漂亮','很不错的说，漂亮，和图片一模一样'),
(null,34,10,'蛋糕超级不错','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,35,11,'蛋糕好好吃(?▽?)','蛋糕好好吃(?▽?)'),
(null,36,12,'这个性价比很高','我觉得挺好吃的，一家三口1.5磅够了'),
(null,37,13,'味道是不错','一小块正好，样子也漂亮，准时'),
(null,38,14,'同学聚会时订的，味道好','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,39,15,'包装都很美','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,40,16,'还会买','家里人很喜欢'),
(null,41,17,'挺好吃的','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,42,18,'很好吃','爸妈都很爱吃，有人过生日还会买'),
(null,43,19,'第二次买了','味道很好，做的也漂亮。'),
(null,44,20,'蛋糕超好吃的','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,45,21,'与图片无差','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,46,22,'最好吃的蛋糕','这个是我吃过的最好吃的蛋糕'),
(null,47,23,'很不错','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,48,24,'蛋糕味道很不错','很好吃，很漂亮'),
(null,49,1,'包装细致','送货准时，蛋糕好吃！'),
(null,50,2,'蛋糕非常好吃','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,51,3,'好吃','全家都很喜欢，4个大人一个小孩都够吃'),
(null,52,4,'非常好吃','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,53,5,'好吃','第三次购买了，6个人吃正好'),
(null,54,6,'非常好吃','非常好吃，以后还会买'),
(null,55,7,'买过很多次','蛋糕味道不错，送货也很准时'),
(null,56,8,'非常好','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,57,9,'超级超级好吃','超级超级好吃，准备再定个'),
(null,58,10,'老客户','这个味道也不错，好评！'),
(null,59,11,'超满意','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,60,12,'第二次买了','第二次买了 好吃！'),
(null,61,13,'味道不错','准时，味道不错，赶上活动买很实惠'),
(null,62,14,'四个人吃刚好','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,63,15,'家里人都非常喜欢吃','第二次购买了'),
(null,64,16,'超好吃','第二次买了，超好吃，比味多美好利来的好吃'),
(null,65,17,'蛋糕味道很不错','蛋糕味道很不错，活动价很划算，分量也够，很棒'),
(null,66,18,'蛋糕很好吃','下单了两个，不同的蛋糕，都按时间送达～真的很方便!口味也不错，家人表示都很喜欢'),
(null,67,19,'蛋糕很好吃','老客户啦 算是蛋糕中新价比高味道又做得好的 喜欢'),
(null,68,20,'口味不错，好吃～','口味不错，好吃～'),
(null,69,21,'非常好吃','经常买，可以现在涨价了。'),
(null,70,22,'超级喜欢','全家都说好！马上过生日的蛋糕锁定你家啦！'),
(null,71,23,'家里人都很喜欢吃','用料十足，性价比太高了'),
(null,72,24,'口感不错','以后还会光临'),
(null,73,1,'老爸很满意','老爸很满意'),
(null,74,2,'非常好','准时，味道也不错'),
(null,75,3,'这个特别好吃','一点不腻，连续点了两次给老公和老妈'),
(null,76,4,'蛋糕非常好吃','蛋糕非常好吃，孩子很高兴。'),
(null,77,5,'好吃','好吃！已经是第五个啦！'),
(null,78,6,'赞的','价格很划算，很精致，送货的大叔特别好哦，因为送早了怕蛋糕坏掉，还特地帮忙送到家里去了，棒棒哒'),
(null,79,7,'非常好吃','推荐这家店铺！'),
(null,80,8,'很好吃','下次还会来。'),
(null,81,9,'好吃','好吃，送货准时'),
(null,82,10,'买来试试','口感比较好，下次还会来光顾的哦~'),
(null,83,11,'送货准时','味道赞，真心不错。'),
(null,84,12,'很好吃','家人都喜欢，一下子就没了，抢了一块来拍照。师傅送得很准时，万分感谢！'),
(null,85,13,'我很喜欢','我很喜欢，配送也很好，客服态度好'),
(null,86,14,'必须好评','味道一致好评，孩子很开心～'),
(null,87,15,'蛋糕很好吃','蛋糕很好吃，蛋糕很好吃'),
(null,88,16,'很好','一百分'),
(null,89,17,'质量很好','原材料讲究，工艺也不错'),
(null,90,18,'品质不错的','品质不错的'),
(null,91,19,'蛋糕味道很好','很好吃……很好吃……'),
(null,92,20,'蛋糕非常好吃','甜而不腻，价格实惠，发货也快，下次还会光顾的。'),
(null,93,21,'合作很多次了','合作很多次了。很好。'),
(null,94,22,'满意','好吃，叉子碟子质量也太好了吧…觉着有点浪费?，家里三个人吃完全吃不完哈哈'),
(null,95,23,'还不错','适合2—3个人的生日聚会'),
(null,96,24,'很好吃','口感很好～做的很漂亮，送的时间太准时了。棒！朋友非常喜欢～'),
(null,97,1,'收到，特别棒！！！','服务很到位，中间还改了一次时间，关键蛋糕也很好吃！满分啊！'),
(null,98,2,'质量很好 ','质量很好 发货快 包装好 服务到位'),
(null,99,3,'第二次买了','第二次买了，真心好吃哦，下午茶棒棒哒'),
(null,100,4,'味道超级棒','用料十足，配送师傅超级棒。继续回购'),
(null,101,5,'会继续关注','配送时间和备注的基本一致，蛋糕用料很好，没有人工奶油'),
(null,59,6,'爸妈都说好吃','买来试吃的，还不错'),
(null,60,7,'第二次买了','从质量到服务到快递都非常满意，这是第二次买了，还会再来'),
(null,61,8,'味道很好','味道很好，家人很喜欢'),
(null,62,9,'蛋糕很好吃','这个味道也不错，好评！'),
(null,63,10,'很好','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,64,11,'质量很好','第二次买了 好吃！'),
(null,65,12,'品质不错的','准时，味道不错，赶上活动买很实惠'),
(null,66,13,'蛋糕味道很好','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,67,14,'蛋糕非常好吃','第二次购买了'),
(null,68,15,'合作很多次了','第二次买了，超好吃，比味多美好利来的好吃'),
(null,69,16,'满意','蛋糕味道很不错，活动价很划算，分量也够，很棒'),
(null,70,17,'还不错','下单了两个，不同的蛋糕，都按时间送达～真的很方便!口味也不错，家人表示都很喜欢'),
(null,71,18,'很好吃','老客户啦 算是蛋糕中新价比高味道又做得好的 喜欢'),
(null,72,19,'收到，特别棒！！！','口味不错，好吃～'),
(null,73,20,'质量很好 ','经常买，可以现在涨价了。'),
(null,74,21,'第二次买了','全家都说好！马上过生日的蛋糕锁定你家啦！'),
(null,75,22,'味道超级棒','用料十足，性价比太高了'),
(null,15,23,'超满意','以后还会光临'),
(null,16,24,'第二次买了','老爸很满意'),
(null,17,1,'味道不错','准时，味道也不错'),
(null,18,2,'四个人吃刚好','一点不腻，连续点了两次给老公和老妈'),
(null,19,3,'家里人都非常喜欢吃','蛋糕非常好吃，孩子很高兴。'),
(null,20,4,'超好吃','好吃！已经是第五个啦！'),
(null,21,5,'蛋糕味道很不错','价格很划算，很精致，送货的大叔特别好哦，因为送早了怕蛋糕坏掉，还特地帮忙送到家里去了，棒棒哒'),
(null,22,6,'蛋糕很好吃','推荐这家店铺！'),
(null,23,7,'蛋糕很好吃','下次还会来。'),
(null,24,8,'口味不错，好吃～','好吃，送货准时'),
(null,25,9,'非常好吃','口感比较好，下次还会来光顾的哦~'),
(null,26,10,'超级喜欢','味道赞，真心不错。'),
(null,27,11,'家里人都很喜欢吃','送的挺快的，蛋糕看起来也不错'),
(null,28,12,'口感不错','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,29,13,'老爸很满意','很不错的说，漂亮，和图片一模一样'),
(null,30,14,'非常好','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,31,15,'这个特别好吃','蛋糕好好吃(?▽?)'),
(null,32,16,'好吃','我觉得挺好吃的，一家三口1.5磅够了'),
(null,38,17,'非常好吃','一小块正好，样子也漂亮，准时'),
(null,39,18,'好好吃','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,40,19,'非常喜欢','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,41,20,'买了三次了','家里人很喜欢'),
(null,42,21,'喜欢','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,43,22,'挺好的','爸妈都很爱吃，有人过生日还会买'),
(null,44,23,'很满意！','味道很好，做的也漂亮。'),
(null,45,24,'漂亮','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,46,1,'蛋糕超级不错','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,47,2,'蛋糕好好吃(?▽?)','这个是我吃过的最好吃的蛋糕'),
(null,48,3,'这个性价比很高','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,49,4,'味道是不错','很好吃，很漂亮'),
(null,50,5,'同学聚会时订的，味道好','送货准时，蛋糕好吃！'),
(null,51,6,'包装都很美','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,52,7,'还会买','全家都很喜欢，4个大人一个小孩都够吃'),
(null,53,8,'挺好吃的','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,54,9,'很好吃','第三次购买了，6个人吃正好'),
(null,55,10,'第二次买了','非常好吃，以后还会买'),
(null,56,11,'蛋糕超好吃的','蛋糕味道不错，送货也很准时'),
(null,57,12,'与图片无差','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,58,13,'超满意，蛋糕非常新鲜','超级超级好吃，准备再定个'),
(null,59,14,'蛋糕真心不错','很好吃，但总体还是很满意的，棒棒哒，还会继续关注的……'),
(null,60,15,'很好吃哟','超满意，蛋糕非常新鲜，好吃也不贵，优惠完大概才50多，超值，家人喜欢，有活动一定会再来买的，很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,61,16,'女朋友收到可喜欢了','蛋糕真心不错，朋友推荐购买的，太划算了，还会继续回购的'),
(null,73,17,'非常好吃','很好吃哟，绵绵的，一磅大概有六寸那么大，非常够吃，最厉害是盘子和叉子都是硬的厚的塑料，非常高端。'),
(null,74,18,'蛋糕好吃','味道也好吃，还按我的要求写了女朋友生日'),
(null,75,19,'赞赞赞～蛋糕很绵软','经过宿舍8个人的一致认同 非常好吃(??ω?)? 非常满意 我的两个室友生日可以说是很圆满了'),
(null,15,20,'味道真的很好吃','蛋糕好吃，吃太多会腻。6寸实际看起来好小好小好小个，不过我们三个人吃够够的了。'),
(null,16,21,'很满意','比较轻口，不会那么腻～味的也可以，价格也合适～各种赞，包装也完美'),
(null,17,22,'味道都很好','买的一磅，免费自动升级到1.5磅，看上去小小的，宿舍6个妹子都够吃。送货准时，给室友过生日的不二之选。'),
(null,18,23,'很好','叉子盘子带标志显高档，味道不错，跟平常买的带蛋糕的不一样，全是乳酪，好吃，一份够6个人吃刚好，差不多了，再吃第二块会腻的'),
(null,19,24,'味道还不错，香浓','一次拍了两款，味道都很好，下次蛋糕继续光顾'),
(null,20,1,'挺好的','提前三周买的，到当天准点送到，很好，味道不错，同事们都赞不绝口'),
(null,21,2,'很好吃的蛋糕','味道还不错，香浓，吃多了有点腻，送货前都打电话确定的，很好，又定了两个……'),
(null,22,3,'蛋糕好好吃的！','挺好的，味道不错。'),
(null,23,4,'超级好吃','很好吃的蛋糕，你值得拥有'),
(null,24,5,'很不错','室友都说好吃 而且分量足 刚打开的时候觉得不大 分起来分了十来个人 奶油很香而且不腻 真的好吃'),
(null,25,6,'味道比较纯正 ','超级负责。这个蛋糕真的超级好吃。还会回购。'),
(null,26,7,'很满意的蛋糕','一直买你们家的蛋糕的，很不错，很喜欢吃～'),
(null,27,8,'好吃','味道比较纯正 但是太甜了太甜了太甜了 重要的话说三遍 有点腻 如果没这么甜就好了'),
(null,28,9,'非常好吃','很满意的蛋糕 妈妈很喜欢 配送准时 赞一个哈'),
(null,29,10,'好好吃','很好吃，同事们都很喜欢。'),
(null,30,11,'非常喜欢','同事们都说很好吃，下次还来买。'),
(null,31,12,'买了三次了','5个人分着吃刚刚好'),
(null,32,13,'喜欢','非常好吃而且奶油的话也非常的甜而不腻希望之后有折扣和活动会继续购买的'),
(null,38,14,'挺好的','好吃的 送的也特别早'),
(null,39,15,'很满意！','孩子很喜欢。早饭有着落了'),
(null,40,16,'漂亮','送的挺快的，蛋糕看起来也不错'),
(null,41,17,'蛋糕超级不错','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,42,18,'蛋糕好好吃(?▽?)','很不错的说，漂亮，和图片一模一样'),
(null,91,19,'这个性价比很高','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,92,20,'味道是不错','蛋糕好好吃(?▽?)'),
(null,93,21,'同学聚会时订的，味道好','我觉得挺好吃的，一家三口1.5磅够了'),
(null,94,22,'包装都很美','一小块正好，样子也漂亮，准时'),
(null,95,23,'还会买','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,96,24,'挺好吃的','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,97,1,'很好吃','家里人很喜欢'),
(null,98,2,'第二次买了','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,99,3,'蛋糕超好吃的','爸妈都很爱吃，有人过生日还会买'),
(null,100,4,'与图片无差','味道很好，做的也漂亮。'),
(null,101,5,'最好吃的蛋糕','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,59,6,'很不错','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,60,7,'蛋糕味道很不错','这个是我吃过的最好吃的蛋糕'),
(null,61,8,'包装细致','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,62,9,'蛋糕非常好吃','很好吃，很漂亮'),
(null,63,10,'好吃','送货准时，蛋糕好吃！'),
(null,64,11,'非常好吃','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,65,12,'好吃','全家都很喜欢，4个大人一个小孩都够吃'),
(null,66,13,'非常好吃','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,67,14,'买过很多次','第三次购买了，6个人吃正好'),
(null,68,15,'非常好','非常好吃，以后还会买'),
(null,69,16,'超级超级好吃','蛋糕味道不错，送货也很准时'),
(null,70,17,'老客户','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,71,18,'超满意','超级超级好吃，准备再定个'),
(null,72,19,'第二次买了','这个味道也不错，好评！'),
(null,73,20,'味道不错','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,74,21,'四个人吃刚好','第二次买了 好吃！'),
(null,75,22,'家里人都非常喜欢吃','准时，味道不错，赶上活动买很实惠'),
(null,15,23,'超好吃','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,16,24,'蛋糕味道很不错','第二次购买了'),
(null,17,1,'蛋糕很好吃','第二次买了，超好吃，比味多美好利来的好吃'),
(null,18,2,'蛋糕很好吃','蛋糕味道很不错，活动价很划算，分量也够，很棒'),
(null,19,3,'口味不错，好吃～','下单了两个，不同的蛋糕，都按时间送达～真的很方便!口味也不错，家人表示都很喜欢'),
(null,20,4,'非常好吃','老客户啦 算是蛋糕中新价比高味道又做得好的 喜欢'),
(null,21,5,'超级喜欢','口味不错，好吃～'),
(null,22,6,'家里人都很喜欢吃','经常买，可以现在涨价了。'),
(null,23,7,'口感不错','全家都说好！马上过生日的蛋糕锁定你家啦！'),
(null,24,8,'老爸很满意','用料十足，性价比太高了'),
(null,25,9,'非常好','以后还会光临'),
(null,26,10,'这个特别好吃','老爸很满意'),
(null,27,11,'蛋糕非常好吃','准时，味道也不错'),
(null,28,12,'好吃','一点不腻，连续点了两次给老公和老妈'),
(null,29,13,'赞的','蛋糕非常好吃，孩子很高兴。'),
(null,30,14,'非常好吃','好吃！已经是第五个啦！'),
(null,31,15,'很好吃','价格很划算，很精致，送货的大叔特别好哦，因为送早了怕蛋糕坏掉，还特地帮忙送到家里去了，棒棒哒'),
(null,32,16,'好吃','推荐这家店铺！'),
(null,38,17,'买来试试','下次还会来。'),
(null,39,18,'送货准时','好吃，送货准时'),
(null,40,19,'很好吃','口感比较好，下次还会来光顾的哦~'),
(null,41,20,'我很喜欢','味道赞，真心不错。'),
(null,42,21,'必须好评','家人都喜欢，一下子就没了，抢了一块来拍照。师傅送得很准时，万分感谢！'),
(null,43,22,'蛋糕很好吃','我很喜欢，配送也很好，客服态度好'),
(null,44,23,'很好','味道一致好评，孩子很开心～'),
(null,45,24,'质量很好','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,46,1,'品质不错的','第三次购买了，6个人吃正好'),
(null,47,2,'蛋糕味道很好','非常好吃，以后还会买'),
(null,48,3,'蛋糕非常好吃','蛋糕味道不错，送货也很准时'),
(null,49,4,'合作很多次了','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,50,5,'满意','超级超级好吃，准备再定个'),
(null,51,6,'还不错','这个味道也不错，好评！'),
(null,52,7,'很好吃','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,53,8,'收到，特别棒！！！','第二次买了 好吃！'),
(null,54,9,'质量很好 ','准时，味道不错，赶上活动买很实惠'),
(null,55,10,'第二次买了','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,56,11,'味道超级棒','第二次购买了'),
(null,57,12,'会继续关注','第二次买了，超好吃，比味多美好利来的好吃'),
(null,58,13,'爸妈都说好吃','同事们都说很好吃，下次还来买。'),
(null,59,14,'第二次买了','5个人分着吃刚刚好'),
(null,60,15,'味道很好','非常好吃而且奶油的话也非常的甜而不腻希望之后有折扣和活动会继续购买的'),
(null,61,16,'蛋糕很好吃','好吃的 送的也特别早'),
(null,73,17,'很好','孩子很喜欢。早饭有着落了'),
(null,74,18,'质量很好','送的挺快的，蛋糕看起来也不错'),
(null,75,19,'品质不错的','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,15,20,'蛋糕味道很好','很不错的说，漂亮，和图片一模一样'),
(null,16,21,'蛋糕非常好吃','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,17,22,'合作很多次了','蛋糕好好吃(?▽?)'),
(null,18,23,'满意','我觉得挺好吃的，一家三口1.5磅够了'),
(null,19,24,'还不错','一小块正好，样子也漂亮，准时'),
(null,20,1,'很好吃','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,21,2,'收到，特别棒！！！','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,22,3,'质量很好 ','家里人很喜欢'),
(null,23,4,'第二次买了','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,24,5,'味道超级棒','爸妈都很爱吃，有人过生日还会买'),
(null,25,6,'超满意','味道很好，做的也漂亮。'),
(null,26,7,'第二次买了','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,27,8,'味道不错','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,28,9,'四个人吃刚好','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,29,10,'家里人都非常喜欢吃','家里人很喜欢'),
(null,30,11,'超好吃','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,31,12,'蛋糕味道很不错','爸妈都很爱吃，有人过生日还会买'),
(null,32,13,'蛋糕很好吃','味道很好，做的也漂亮。'),
(null,38,14,'蛋糕很好吃','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,39,15,'口味不错，好吃～','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,40,16,'非常好吃','这个是我吃过的最好吃的蛋糕'),
(null,41,17,'超级喜欢','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,6,18,'家里人都很喜欢吃','很好吃，很漂亮'),
(null,7,19,'口感不错','送货准时，蛋糕好吃！'),
(null,8,20,'老爸很满意','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,9,21,'非常好','全家都很喜欢，4个大人一个小孩都够吃'),
(null,10,22,'质量很好 ','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,11,23,'第二次买了','第三次购买了，6个人吃正好'),
(null,12,24,'味道超级棒','非常好吃，以后还会买'),
(null,13,1,'会继续关注','蛋糕味道不错，送货也很准时'),
(null,14,2,'爸妈都说好吃','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,15,3,'第二次买了','超级超级好吃，准备再定个'),
(null,16,4,'味道很好','这个味道也不错，好评！'),
(null,17,5,'蛋糕很好吃','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,18,6,'很好','甜而不腻，价格实惠，发货也快，下次还会光顾的。'),
(null,19,7,'质量很好','合作很多次了。很好。'),
(null,20,8,'品质不错的','好吃，叉子碟子质量也太好了吧…觉着有点浪费?，家里三个人吃完全吃不完哈哈'),
(null,21,9,'蛋糕味道很好','适合2—3个人的生日聚会'),
(null,22,10,'蛋糕非常好吃','口感很好～做的很漂亮，送的时间太准时了。棒！朋友非常喜欢～'),
(null,23,11,'合作很多次了','服务很到位，中间还改了一次时间，关键蛋糕也很好吃！满分啊！'),
(null,24,12,'满意','质量很好 发货快 包装好 服务到位'),
(null,25,13,'还不错','第二次买了，真心好吃哦，下午茶棒棒哒'),
(null,26,14,'很好吃','用料十足，配送师傅超级棒。继续回购'),
(null,27,15,'收到，特别棒！！！','配送时间和备注的基本一致，蛋糕用料很好，没有人工奶油'),
(null,28,16,'质量很好 ','买来试吃的，还不错'),
(null,29,17,'第二次买了','从质量到服务到快递都非常满意，这是第二次买了，还会再来'),
(null,30,18,'味道超级棒','味道很好，家人很喜欢'),
(null,31,19,'超满意','这个味道也不错，好评！'),
(null,32,20,'第二次买了','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,33,21,'味道不错','第二次买了 好吃！'),
(null,34,22,'四个人吃刚好','准时，味道不错，赶上活动买很实惠'),
(null,35,23,'家里人都非常喜欢吃','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,36,24,'超好吃','第二次购买了'),
(null,37,1,'蛋糕味道很不错','第二次买了，超好吃，比味多美好利来的好吃'),
(null,38,2,'蛋糕很好吃','蛋糕味道很不错，活动价很划算，分量也够，很棒'),
(null,39,3,'蛋糕很好吃','下单了两个，不同的蛋糕，都按时间送达～真的很方便!口味也不错，家人表示都很喜欢'),
(null,40,4,'口味不错，好吃～','老客户啦 算是蛋糕中新价比高味道又做得好的 喜欢'),
(null,41,5,'非常好吃','口味不错，好吃～'),
(null,42,6,'超级喜欢','经常买，可以现在涨价了。'),
(null,43,7,'家里人都很喜欢吃','全家都说好！马上过生日的蛋糕锁定你家啦！'),
(null,44,8,'口感不错','用料十足，性价比太高了'),
(null,45,9,'老爸很满意','以后还会光临'),
(null,46,10,'非常好','老爸很满意'),
(null,47,11,'这个特别好吃','准时，味道也不错'),
(null,48,12,'好吃','一点不腻，连续点了两次给老公和老妈'),
(null,49,13,'非常好吃','蛋糕非常好吃，孩子很高兴。'),
(null,50,14,'好好吃','好吃！已经是第五个啦！'),
(null,51,15,'非常喜欢','价格很划算，很精致，送货的大叔特别好哦，因为送早了怕蛋糕坏掉，还特地帮忙送到家里去了，棒棒哒'),
(null,52,16,'买了三次了','推荐这家店铺！'),
(null,53,17,'喜欢','下次还会来。'),
(null,54,18,'挺好的','好吃，送货准时'),
(null,55,19,'很满意！','口感比较好，下次还会来光顾的哦~'),
(null,56,20,'漂亮','味道赞，真心不错。'),
(null,57,21,'蛋糕超级不错','送的挺快的，蛋糕看起来也不错'),
(null,58,22,'蛋糕好好吃(?▽?)','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,59,23,'这个性价比很高','很不错的说，漂亮，和图片一模一样'),
(null,60,24,'味道是不错','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,61,1,'同学聚会时订的，味道好','蛋糕好好吃(?▽?)'),
(null,62,2,'包装都很美','我觉得挺好吃的，一家三口1.5磅够了'),
(null,63,3,'还会买','一小块正好，样子也漂亮，准时'),
(null,64,4,'挺好吃的','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,65,5,'很好吃','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,66,6,'第二次买了','家里人很喜欢'),
(null,67,7,'蛋糕超好吃的','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,68,8,'与图片无差','爸妈都很爱吃，有人过生日还会买'),
(null,69,9,'超满意，蛋糕非常新鲜','味道很好，做的也漂亮。'),
(null,70,10,'蛋糕真心不错','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,71,11,'很好吃哟','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,72,12,'女朋友收到可喜欢了','这个是我吃过的最好吃的蛋糕'),
(null,73,13,'非常好吃','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,74,14,'蛋糕好吃','很好吃，很漂亮'),
(null,75,15,'赞赞赞～蛋糕很绵软','送货准时，蛋糕好吃！'),
(null,76,16,'味道真的很好吃','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,77,17,'很满意','全家都很喜欢，4个大人一个小孩都够吃'),
(null,78,18,'味道都很好','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,79,19,'很好','第三次购买了，6个人吃正好'),
(null,80,20,'味道还不错，香浓','非常好吃，以后还会买'),
(null,81,21,'挺好的','蛋糕味道不错，送货也很准时'),
(null,82,22,'很好吃的蛋糕','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,83,23,'蛋糕好好吃的！','超级超级好吃，准备再定个'),
(null,84,24,'超级好吃','很好吃，但总体还是很满意的，棒棒哒，还会继续关注的……'),
(null,85,1,'很不错','超满意，蛋糕非常新鲜，好吃也不贵，优惠完大概才50多，超值，家人喜欢，有活动一定会再来买的，很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,86,2,'味道比较纯正 ','蛋糕真心不错，朋友推荐购买的，太划算了，还会继续回购的'),
(null,87,3,'很满意的蛋糕','很好吃哟，绵绵的，一磅大概有六寸那么大，非常够吃，最厉害是盘子和叉子都是硬的厚的塑料，非常高端。'),
(null,88,4,'好吃','味道也好吃，还按我的要求写了女朋友生日'),
(null,89,5,'非常好吃','经过宿舍8个人的一致认同 非常好吃(??ω?)? 非常满意 我的两个室友生日可以说是很圆满了'),
(null,90,6,'好好吃','蛋糕好吃，吃太多会腻。6寸实际看起来好小好小好小个，不过我们三个人吃够够的了。'),
(null,91,7,'非常喜欢','比较轻口，不会那么腻～味的也可以，价格也合适～各种赞，包装也完美'),
(null,92,8,'买了三次了','买的一磅，免费自动升级到1.5磅，看上去小小的，宿舍6个妹子都够吃。送货准时，给室友过生日的不二之选。'),
(null,93,9,'喜欢','叉子盘子带标志显高档，味道不错，跟平常买的带蛋糕的不一样，全是乳酪，好吃，一份够6个人吃刚好，差不多了，再吃第二块会腻的'),
(null,94,10,'挺好的','一次拍了两款，味道都很好，下次蛋糕继续光顾'),
(null,95,11,'很满意！','提前三周买的，到当天准点送到，很好，味道不错，同事们都赞不绝口'),
(null,96,12,'漂亮','味道还不错，香浓，吃多了有点腻，送货前都打电话确定的，很好，又定了两个……'),
(null,97,13,'蛋糕超级不错','挺好的，味道不错。'),
(null,98,14,'蛋糕好好吃(?▽?)','很好吃的蛋糕，你值得拥有'),
(null,99,15,'这个性价比很高','室友都说好吃 而且分量足 刚打开的时候觉得不大 分起来分了十来个人 奶油很香而且不腻 真的好吃'),
(null,100,16,'味道是不错','超级负责。这个蛋糕真的超级好吃。还会回购。'),
(null,101,17,'同学聚会时订的，味道好','一直买你们家的蛋糕的，很不错，很喜欢吃～'),
(null,59,18,'包装都很美','味道比较纯正 但是太甜了太甜了太甜了 重要的话说三遍 有点腻 如果没这么甜就好了'),
(null,60,19,'还会买','很满意的蛋糕 妈妈很喜欢 配送准时 赞一个哈'),
(null,61,20,'挺好吃的','很好吃，同事们都很喜欢。'),
(null,62,21,'很好吃','同事们都说很好吃，下次还来买。'),
(null,63,22,'第二次买了','5个人分着吃刚刚好'),
(null,64,23,'蛋糕超好吃的','非常好吃而且奶油的话也非常的甜而不腻希望之后有折扣和活动会继续购买的'),
(null,65,24,'与图片无差','好吃的 送的也特别早'),
(null,66,1,'最好吃的蛋糕','孩子很喜欢。早饭有着落了'),
(null,67,2,'很不错','送的挺快的，蛋糕看起来也不错'),
(null,68,3,'蛋糕味道很不错','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,69,4,'包装细致','很不错的说，漂亮，和图片一模一样'),
(null,70,5,'蛋糕非常好吃','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,71,6,'好吃','蛋糕好好吃(?▽?)'),
(null,72,7,'非常好吃','我觉得挺好吃的，一家三口1.5磅够了'),
(null,73,8,'好吃','一小块正好，样子也漂亮，准时'),
(null,74,9,'非常好吃','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,75,10,'买过很多次','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,15,11,'非常好','家里人很喜欢'),
(null,16,12,'超级超级好吃','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,17,13,'老客户','爸妈都很爱吃，有人过生日还会买'),
(null,18,14,'超满意','味道很好，做的也漂亮。'),
(null,19,15,'第二次买了','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,20,16,'味道不错','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,21,17,'四个人吃刚好','这个是我吃过的最好吃的蛋糕'),
(null,22,18,'家里人都非常喜欢吃','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,23,19,'超好吃','很好吃，很漂亮'),
(null,24,20,'蛋糕味道很不错','送货准时，蛋糕好吃！'),
(null,25,21,'蛋糕很好吃','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,26,22,'蛋糕很好吃','全家都很喜欢，4个大人一个小孩都够吃'),
(null,27,23,'口味不错，好吃～','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,28,24,'非常好吃','第三次购买了，6个人吃正好'),
(null,29,1,'超级喜欢','非常好吃，以后还会买'),
(null,30,2,'家里人都很喜欢吃','蛋糕味道不错，送货也很准时'),
(null,31,3,'口感不错','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,32,4,'老爸很满意','超级超级好吃，准备再定个'),
(null,38,5,'非常好','这个味道也不错，好评！'),
(null,39,6,'这个特别好吃','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,40,7,'蛋糕非常好吃','第二次买了 好吃！'),
(null,41,8,'好吃','准时，味道不错，赶上活动买很实惠'),
(null,42,9,'赞的','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,43,10,'非常好吃','第二次购买了'),
(null,44,11,'很好吃','第二次买了，超好吃，比味多美好利来的好吃'),
(null,45,12,'好吃','蛋糕味道很不错，活动价很划算，分量也够，很棒'),
(null,46,13,'买来试试','下单了两个，不同的蛋糕，都按时间送达～真的很方便!口味也不错，家人表示都很喜欢'),
(null,47,14,'送货准时','老客户啦 算是蛋糕中新价比高味道又做得好的 喜欢'),
(null,48,15,'很好吃','口味不错，好吃～'),
(null,49,16,'我很喜欢','经常买，可以现在涨价了。'),
(null,50,17,'必须好评','全家都说好！马上过生日的蛋糕锁定你家啦！'),
(null,51,18,'蛋糕很好吃','用料十足，性价比太高了'),
(null,52,19,'很好','以后还会光临'),
(null,53,20,'质量很好','老爸很满意'),
(null,54,21,'品质不错的','准时，味道也不错'),
(null,55,22,'蛋糕味道很好','一点不腻，连续点了两次给老公和老妈'),
(null,56,23,'蛋糕非常好吃','蛋糕非常好吃，孩子很高兴。'),
(null,57,24,'合作很多次了','好吃！已经是第五个啦！'),
(null,58,1,'满意','价格很划算，很精致，送货的大叔特别好哦，因为送早了怕蛋糕坏掉，还特地帮忙送到家里去了，棒棒哒'),
(null,59,2,'还不错','推荐这家店铺！'),
(null,60,3,'很好吃','下次还会来。'),
(null,61,4,'收到，特别棒！！！','好吃，送货准时'),
(null,73,5,'质量很好 ','口感比较好，下次还会来光顾的哦~'),
(null,74,6,'第二次买了','味道赞，真心不错。'),
(null,75,7,'味道超级棒','家人都喜欢，一下子就没了，抢了一块来拍照。师傅送得很准时，万分感谢！'),
(null,15,8,'会继续关注','我很喜欢，配送也很好，客服态度好'),
(null,16,9,'爸妈都说好吃','味道一致好评，孩子很开心～'),
(null,17,10,'第二次买了','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,18,11,'味道很好','第三次购买了，6个人吃正好'),
(null,19,12,'蛋糕很好吃','非常好吃，以后还会买'),
(null,20,13,'很好','蛋糕味道不错，送货也很准时'),
(null,21,14,'质量很好','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,22,15,'品质不错的','超级超级好吃，准备再定个'),
(null,23,16,'蛋糕味道很好','这个味道也不错，好评！'),
(null,24,17,'蛋糕非常好吃','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,25,18,'合作很多次了','第二次买了 好吃！'),
(null,26,19,'满意','准时，味道不错，赶上活动买很实惠'),
(null,27,20,'还不错','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,28,21,'很好吃','第二次购买了'),
(null,29,22,'收到，特别棒！！！','第二次买了，超好吃，比味多美好利来的好吃'),
(null,30,23,'质量很好 ','同事们都说很好吃，下次还来买。'),
(null,31,24,'第二次买了','5个人分着吃刚刚好'),
(null,32,1,'味道超级棒','非常好吃而且奶油的话也非常的甜而不腻希望之后有折扣和活动会继续购买的'),
(null,38,2,'超满意','好吃的 送的也特别早'),
(null,39,3,'第二次买了','孩子很喜欢。早饭有着落了'),
(null,40,4,'味道不错','送的挺快的，蛋糕看起来也不错'),
(null,41,5,'四个人吃刚好','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,42,6,'家里人都非常喜欢吃','很不错的说，漂亮，和图片一模一样'),
(null,91,7,'超好吃','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,92,8,'蛋糕味道很不错','蛋糕好好吃(?▽?)'),
(null,93,9,'蛋糕很好吃','我觉得挺好吃的，一家三口1.5磅够了'),
(null,94,10,'蛋糕很好吃','一小块正好，样子也漂亮，准时'),
(null,95,11,'口味不错，好吃～','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,96,12,'非常好吃','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,97,13,'超级喜欢','家里人很喜欢'),
(null,98,14,'家里人都很喜欢吃','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,99,15,'口感不错','爸妈都很爱吃，有人过生日还会买'),
(null,100,16,'还会买','味道很好，做的也漂亮。'),
(null,101,17,'挺好吃的','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,59,18,'很好吃','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,60,19,'第二次买了','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,61,20,'蛋糕超好吃的','家里人很喜欢'),
(null,62,21,'与图片无差','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,25,22,'最好吃的蛋糕','爸妈都很爱吃，有人过生日还会买'),
(null,26,23,'四个人吃刚好','味道很好，做的也漂亮。'),
(null,27,24,'家里人都非常喜欢吃','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,28,1,'超好吃','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,29,2,'蛋糕味道很不错','这个是我吃过的最好吃的蛋糕'),
(null,30,3,'蛋糕很好吃','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,31,4,'蛋糕很好吃','很好吃，很漂亮'),
(null,32,5,'买来试试','送货准时，蛋糕好吃！'),
(null,38,6,'送货准时','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,39,7,'很好吃','全家都很喜欢，4个大人一个小孩都够吃'),
(null,40,8,'我很喜欢','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,41,9,'必须好评','第三次购买了，6个人吃正好'),
(null,6,10,'蛋糕很好吃','非常好吃，以后还会买'),
(null,7,11,'很好','蛋糕味道不错，送货也很准时'),
(null,8,12,'质量很好','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,9,13,'品质不错的','超级超级好吃，准备再定个'),
(null,10,14,'非常好吃','一小块正好，样子也漂亮，准时'),
(null,11,15,'超级喜欢','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,12,16,'家里人都很喜欢吃','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,13,17,'口感不错','家里人很喜欢'),
(null,14,18,'老爸很满意','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,15,19,'非常好','爸妈都很爱吃，有人过生日还会买'),
(null,16,20,'这个特别好吃','味道很好，做的也漂亮。'),
(null,17,21,'蛋糕很好吃','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,18,22,'很好','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,19,23,'质量很好','这个是我吃过的最好吃的蛋糕'),
(null,20,24,'品质不错的','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,21,1,'蛋糕味道很好','很好吃，很漂亮'),
(null,22,2,'蛋糕非常好吃','送货准时，蛋糕好吃！'),
(null,23,3,'合作很多次了','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,24,4,'满意','全家都很喜欢，4个大人一个小孩都够吃'),
(null,25,5,'还不错','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,26,6,'很好吃','第三次购买了，6个人吃正好'),
(null,25,7,'收到，特别棒！！！','非常好吃，以后还会买'),
(null,26,8,'老客户','蛋糕味道不错，送货也很准时'),
(null,27,9,'超满意','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,28,10,'第二次买了','超级超级好吃，准备再定个'),
(null,29,11,'味道不错','这个味道也不错，好评！'),
(null,30,12,'四个人吃刚好','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,31,13,'家里人都非常喜欢吃','第二次买了 好吃！'),
(null,32,14,'超好吃','准时，味道不错，赶上活动买很实惠'),
(null,38,15,'蛋糕味道很不错','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,39,16,'蛋糕很好吃','第二次购买了'),
(null,40,17,'蛋糕很好吃','第二次买了，超好吃，比味多美好利来的好吃'),
(null,41,18,'口味不错，好吃～','蛋糕味道很不错，活动价很划算，分量也够，很棒'),
(null,6,19,'非常好吃','下单了两个，不同的蛋糕，都按时间送达～真的很方便!口味也不错，家人表示都很喜欢'),
(null,7,20,'超级喜欢','老客户啦 算是蛋糕中新价比高味道又做得好的 喜欢'),
(null,8,21,'家里人都很喜欢吃','口味不错，好吃～'),
(null,9,22,'口感不错','经常买，可以现在涨价了。'),
(null,10,23,'老爸很满意','全家都说好！马上过生日的蛋糕锁定你家啦！'),
(null,11,24,'非常好','用料十足，性价比太高了'),
(null,12,1,'这个特别好吃','以后还会光临'),
(null,13,2,'蛋糕非常好吃','老爸很满意'),
(null,14,3,'好吃','准时，味道也不错'),
(null,15,4,'赞的','一点不腻，连续点了两次给老公和老妈'),
(null,16,5,'非常好吃','蛋糕非常好吃，孩子很高兴。'),
(null,17,6,'很好吃','好吃！已经是第五个啦！'),
(null,18,7,'好吃','价格很划算，很精致，送货的大叔特别好哦，因为送早了怕蛋糕坏掉，还特地帮忙送到家里去了，棒棒哒'),
(null,19,8,'买来试试','推荐这家店铺！'),
(null,20,9,'送货准时','下次还会来。'),
(null,21,10,'很好吃','好吃，送货准时'),
(null,22,11,'我很喜欢','口感比较好，下次还会来光顾的哦~'),
(null,23,12,'必须好评','味道赞，真心不错。'),
(null,24,13,'蛋糕很好吃','家人都喜欢，一下子就没了，抢了一块来拍照。师傅送得很准时，万分感谢！'),
(null,25,14,'很好','我很喜欢，配送也很好，客服态度好'),
(null,26,15,'质量很好','味道一致好评，孩子很开心～'),
(null,6,16,'品质不错的','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,7,17,'蛋糕味道很好','第三次购买了，6个人吃正好'),
(null,8,18,'蛋糕非常好吃','非常好吃，以后还会买'),
(null,9,19,'合作很多次了','蛋糕味道不错，送货也很准时'),
(null,10,20,'满意','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,11,21,'还不错','超级超级好吃，准备再定个'),
(null,12,22,'很好吃','这个味道也不错，好评！'),
(null,13,23,'收到，特别棒！！！','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,14,24,'质量很好 ','第二次买了 好吃！'),
(null,15,1,'第二次买了','准时，味道不错，赶上活动买很实惠'),
(null,16,2,'味道超级棒','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,17,3,'会继续关注','第二次购买了'),
(null,18,4,'爸妈都说好吃','第二次买了，超好吃，比味多美好利来的好吃'),
(null,19,5,'第二次买了','同事们都说很好吃，下次还来买。'),
(null,20,6,'味道很好','5个人分着吃刚刚好'),
(null,21,7,'蛋糕很好吃','非常好吃而且奶油的话也非常的甜而不腻希望之后有折扣和活动会继续购买的'),
(null,22,8,'很好','好吃的 送的也特别早'),
(null,23,9,'质量很好','孩子很喜欢。早饭有着落了'),
(null,24,10,'品质不错的','送的挺快的，蛋糕看起来也不错'),
(null,25,11,'蛋糕味道很好','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,52,12,'蛋糕非常好吃','很不错的说，漂亮，和图片一模一样'),
(null,53,13,'合作很多次了','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,54,14,'满意','蛋糕好好吃(?▽?)'),
(null,55,15,'还不错','我觉得挺好吃的，一家三口1.5磅够了'),
(null,56,16,'很好吃','一小块正好，样子也漂亮，准时'),
(null,57,17,'收到，特别棒！！！','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,58,18,'质量很好 ','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,59,19,'第二次买了','家里人很喜欢'),
(null,60,20,'味道超级棒','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,61,21,'超满意','爸妈都很爱吃，有人过生日还会买'),
(null,62,22,'第二次买了','味道很好，做的也漂亮。'),
(null,63,23,'味道不错','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,64,24,'四个人吃刚好','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,65,6,'家里人都非常喜欢吃','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,66,7,'超好吃','家里人很喜欢'),
(null,67,8,'蛋糕味道很不错','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,68,9,'蛋糕很好吃','爸妈都很爱吃，有人过生日还会买'),
(null,69,10,'蛋糕很好吃','味道很好，做的也漂亮。'),
(null,70,11,'口味不错，好吃～','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,71,12,'非常好吃','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,72,13,'超级喜欢','这个是我吃过的最好吃的蛋糕'),
(null,73,14,'家里人都很喜欢吃','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,74,15,'口感不错','很好吃，很漂亮'),
(null,75,16,'还会买','送货准时，蛋糕好吃！'),
(null,76,17,'挺好吃的','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,77,18,'很好吃','全家都很喜欢，4个大人一个小孩都够吃'),
(null,78,19,'第二次买了','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,79,20,'蛋糕超好吃的','第三次购买了，6个人吃正好'),
(null,80,21,'与图片无差','非常好吃，以后还会买'),
(null,81,11,'最好吃的蛋糕','蛋糕味道不错，送货也很准时'),
(null,82,12,'四个人吃刚好','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,83,13,'家里人都非常喜欢吃','超级超级好吃，准备再定个'),
(null,84,14,'超好吃','这个味道也不错，好评！'),
(null,85,15,'蛋糕味道很不错','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,86,16,'蛋糕很好吃','甜而不腻，价格实惠，发货也快，下次还会光顾的。'),
(null,87,17,'蛋糕很好吃','蛋糕味道不错，送货也很准时'),
(null,88,18,'买来试试','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,89,19,'送货准时','超级超级好吃，准备再定个'),
(null,90,20,'很好吃','很好吃，但总体还是很满意的，棒棒哒，还会继续关注的……'),
(null,91,21,'我很喜欢','超满意，蛋糕非常新鲜，好吃也不贵，优惠完大概才50多，超值，家人喜欢，有活动一定会再来买的，很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,92,22,'必须好评','蛋糕真心不错，朋友推荐购买的，太划算了，还会继续回购的'),
(null,93,23,'蛋糕很好吃','很好吃哟，绵绵的，一磅大概有六寸那么大，非常够吃，最厉害是盘子和叉子都是硬的厚的塑料，非常高端。'),
(null,94,24,'很好','味道也好吃，还按我的要求写了女朋友生日'),
(null,95,6,'质量很好','经过宿舍8个人的一致认同 非常好吃(??ω?)? 非常满意 我的两个室友生日可以说是很圆满了'),
(null,96,7,'品质不错的','蛋糕好吃，吃太多会腻。6寸实际看起来好小好小好小个，不过我们三个人吃够够的了。'),
(null,97,8,'非常好吃','比较轻口，不会那么腻～味的也可以，价格也合适～各种赞，包装也完美'),
(null,98,9,'超级喜欢','买的一磅，免费自动升级到1.5磅，看上去小小的，宿舍6个妹子都够吃。送货准时，给室友过生日的不二之选。'),
(null,99,10,'家里人都很喜欢吃','叉子盘子带标志显高档，味道不错，跟平常买的带蛋糕的不一样，全是乳酪，好吃，一份够6个人吃刚好，差不多了，再吃第二块会腻的'),
(null,100,11,'口感不错','一次拍了两款，味道都很好，下次蛋糕继续光顾'),
(null,101,12,'老爸很满意','提前三周买的，到当天准点送到，很好，味道不错，同事们都赞不绝口'),
(null,59,13,'非常好','味道还不错，香浓，吃多了有点腻，送货前都打电话确定的，很好，又定了两个……'),
(null,60,14,'这个特别好吃','挺好的，味道不错。'),
(null,52,15,'蛋糕很好吃','很好吃的蛋糕，你值得拥有'),
(null,53,16,'很好','室友都说好吃 而且分量足 刚打开的时候觉得不大 分起来分了十来个人 奶油很香而且不腻 真的好吃'),
(null,54,17,'质量很好','超级负责。这个蛋糕真的超级好吃。还会回购。'),
(null,55,18,'品质不错的','一直买你们家的蛋糕的，很不错，很喜欢吃～'),
(null,56,19,'蛋糕味道很好','味道比较纯正 但是太甜了太甜了太甜了 重要的话说三遍 有点腻 如果没这么甜就好了'),
(null,57,20,'蛋糕非常好吃','很满意的蛋糕 妈妈很喜欢 配送准时 赞一个哈'),
(null,58,21,'合作很多次了','很好吃，同事们都很喜欢。'),
(null,59,22,'满意','同事们都说很好吃，下次还来买。'),
(null,60,23,'还不错','5个人分着吃刚刚好'),
(null,61,24,'很好吃','非常好吃而且奶油的话也非常的甜而不腻希望之后有折扣和活动会继续购买的'),
(null,62,1,'收到，特别棒！！！','好吃的 送的也特别早'),
(null,63,2,'超满意，蛋糕非常新鲜','孩子很喜欢。早饭有着落了'),
(null,64,3,'蛋糕真心不错','送的挺快的，蛋糕看起来也不错'),
(null,65,4,'很好吃哟','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,66,5,'女朋友收到可喜欢了','很不错的说，漂亮，和图片一模一样'),
(null,67,6,'非常好吃','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,68,7,'蛋糕好吃','蛋糕好好吃(?▽?)'),
(null,69,8,'赞赞赞～蛋糕很绵软','我觉得挺好吃的，一家三口1.5磅够了'),
(null,70,9,'味道真的很好吃','一小块正好，样子也漂亮，准时'),
(null,71,10,'很满意','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,72,11,'味道都很好','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,73,12,'很好','家里人很喜欢'),
(null,74,13,'味道还不错，香浓','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,75,14,'挺好的','爸妈都很爱吃，有人过生日还会买'),
(null,76,15,'很好吃的蛋糕','味道很好，做的也漂亮。'),
(null,77,16,'蛋糕好好吃的！','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,78,17,'超级好吃','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,79,18,'很不错','这个是我吃过的最好吃的蛋糕'),
(null,80,19,'味道比较纯正 ','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,81,20,'很满意的蛋糕','很好吃，很漂亮'),
(null,82,21,'好吃','送货准时，蛋糕好吃！'),
(null,83,1,'非常好吃','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,84,2,'好好吃','全家都很喜欢，4个大人一个小孩都够吃'),
(null,85,3,'非常喜欢','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,86,4,'买了三次了','第三次购买了，6个人吃正好'),
(null,87,5,'喜欢','非常好吃，以后还会买'),
(null,88,6,'挺好的','蛋糕味道不错，送货也很准时'),
(null,89,7,'很满意！','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,90,8,'漂亮','超级超级好吃，准备再定个'),
(null,91,9,'蛋糕超级不错','这个味道也不错，好评！'),
(null,92,10,'蛋糕好好吃(?▽?)','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,93,11,'这个性价比很高','第二次买了 好吃！'),
(null,94,12,'味道是不错','准时，味道不错，赶上活动买很实惠'),
(null,95,13,'同学聚会时订的，味道好','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,96,14,'包装都很美','第二次购买了'),
(null,97,15,'还会买','第二次买了，超好吃，比味多美好利来的好吃'),
(null,98,16,'挺好吃的','蛋糕味道很不错，活动价很划算，分量也够，很棒'),
(null,99,17,'很好吃','下单了两个，不同的蛋糕，都按时间送达～真的很方便!口味也不错，家人表示都很喜欢'),
(null,100,16,'第二次买了','老客户啦 算是蛋糕中新价比高味道又做得好的 喜欢'),
(null,101,15,'蛋糕超好吃的','口味不错，好吃～'),
(null,59,14,'与图片无差','经常买，可以现在涨价了。'),
(null,60,13,'最好吃的蛋糕','全家都说好！马上过生日的蛋糕锁定你家啦！'),
(null,19,12,'很不错','用料十足，性价比太高了'),
(null,20,11,'蛋糕味道很不错','以后还会光临'),
(null,21,10,'包装细致','老爸很满意'),
(null,22,9,'蛋糕非常好吃','准时，味道也不错'),
(null,23,8,'好吃','一点不腻，连续点了两次给老公和老妈'),
(null,24,18,'非常好吃','蛋糕非常好吃，孩子很高兴。'),
(null,25,19,'好吃','好吃！已经是第五个啦！'),
(null,26,20,'非常好吃','价格很划算，很精致，送货的大叔特别好哦，因为送早了怕蛋糕坏掉，还特地帮忙送到家里去了，棒棒哒'),
(null,6,21,'买过很多次','推荐这家店铺！'),
(null,7,22,'非常好','下次还会来。'),
(null,8,23,'超级超级好吃','好吃，送货准时'),
(null,9,24,'老客户','口感比较好，下次还会来光顾的哦~'),
(null,10,1,'超满意','味道赞，真心不错。'),
(null,11,2,'第二次买了','家人都喜欢，一下子就没了，抢了一块来拍照。师傅送得很准时，万分感谢！'),
(null,12,3,'味道不错','我很喜欢，配送也很好，客服态度好'),
(null,13,4,'四个人吃刚好','味道一致好评，孩子很开心～'),
(null,14,5,'家里人都非常喜欢吃','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,15,6,'超好吃','第三次购买了，6个人吃正好'),
(null,16,7,'蛋糕味道很不错','非常好吃，以后还会买'),
(null,17,8,'蛋糕很好吃','蛋糕味道不错，送货也很准时'),
(null,18,9,'蛋糕很好吃','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,19,10,'口味不错，好吃～','超级超级好吃，准备再定个'),
(null,20,11,'非常好吃','这个味道也不错，好评！'),
(null,21,12,'超级喜欢','蛋糕非常新鲜，超值，家人喜欢，有活动一定会再来买的'),
(null,22,13,'家里人都很喜欢吃','第二次买了 好吃！'),
(null,23,14,'口感不错','准时，味道不错，赶上活动买很实惠'),
(null,24,15,'老爸很满意','很小的蛋糕，但是很有份量，四个人吃刚好，也不腻，很漂亮哦'),
(null,25,16,'非常好','第二次购买了'),
(null,52,17,'这个特别好吃','第二次买了，超好吃，比味多美好利来的好吃'),
(null,53,18,'蛋糕非常好吃','同事们都说很好吃，下次还来买。'),
(null,54,19,'好吃','5个人分着吃刚刚好'),
(null,55,20,'赞的','非常好吃而且奶油的话也非常的甜而不腻希望之后有折扣和活动会继续购买的'),
(null,56,21,'非常好吃','好吃的 送的也特别早'),
(null,57,1,'很好吃','孩子很喜欢。早饭有着落了'),
(null,58,2,'好吃','送的挺快的，蛋糕看起来也不错'),
(null,59,3,'买来试试','送到时间很准时，保护措施很完善，服务态度好，送了优惠券，而且蛋糕也很惊艳，口感很扎实，很可惜被儿子摔了一下，样子有点破坏掉了，就没拍照片了'),
(null,60,18,'送货准时','很不错的说，漂亮，和图片一模一样'),
(null,61,19,'很好吃','味道很喜欢，甜而不腻。快递员送货准时。很满意。'),
(null,62,20,'我很喜欢','蛋糕好好吃(?▽?)'),
(null,63,21,'必须好评','我觉得挺好吃的，一家三口1.5磅够了'),
(null,64,22,'蛋糕很好吃','一小块正好，样子也漂亮，准时'),
(null,65,23,'很好','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,66,24,'质量很好','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,67,1,'品质不错的','家里人很喜欢'),
(null,68,2,'蛋糕味道很好','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,69,3,'蛋糕非常好吃','爸妈都很爱吃，有人过生日还会买'),
(null,70,4,'合作很多次了','味道很好，做的也漂亮。'),
(null,71,5,'满意','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,72,6,'还不错','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,73,7,'很好吃','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,74,8,'收到，特别棒！！！','家里人很喜欢'),
(null,75,9,'质量很好 ','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,76,10,'第二次买了','爸妈都很爱吃，有人过生日还会买'),
(null,77,11,'味道超级棒','味道很好，做的也漂亮。'),
(null,78,12,'会继续关注','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,79,13,'爸妈都说好吃','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,80,14,'第二次买了','这个是我吃过的最好吃的蛋糕'),
(null,81,15,'味道很好','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,82,16,'蛋糕很好吃','很好吃，很漂亮'),
(null,83,17,'很好','送货准时，蛋糕好吃！'),
(null,84,18,'质量很好','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,85,19,'品质不错的','全家都很喜欢，4个大人一个小孩都够吃'),
(null,86,20,'蛋糕味道很好','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,87,21,'蛋糕非常好吃','第三次购买了，6个人吃正好'),
(null,88,1,'合作很多次了','非常好吃，以后还会买'),
(null,89,2,'满意','蛋糕味道不错，送货也很准时'),
(null,90,3,'还不错','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,91,17,'很好吃','超级超级好吃，准备再定个'),
(null,92,18,'收到，特别棒！！！','一小块正好，样子也漂亮，准时'),
(null,93,19,'质量很好 ','合口味。送达及时！预定时客服也非常耐心。总之非常好！值得推荐！'),
(null,94,20,'第二次买了','包装都很美看着高大上，蛋糕超好吃的，奶味很足，甜而不腻，家人都说好吃'),
(null,95,21,'味道超级棒','家里人很喜欢'),
(null,96,22,'超满意','蛋糕好好吃O(∩_∩)O哈哈~'),
(null,97,23,'第二次买了','爸妈都很爱吃，有人过生日还会买'),
(null,98,24,'味道不错','味道很好，做的也漂亮。'),
(null,99,6,'四个人吃刚好','奶味很足，甜而不腻，家人都说好吃，价格也很给力下次还会再来'),
(null,100,7,'家里人都非常喜欢吃','蛋糕日期新鲜，很棒。本人不是托，良心评价，祝生意兴隆，推出更多美味蛋糕'),
(null,101,8,'超好吃','这个是我吃过的最好吃的蛋糕'),
(null,59,9,'蛋糕味道很不错','还有一个下月妹妹生日送货，小侄女赞不绝口，停不下来了，哈哈。'),
(null,60,10,'蛋糕很好吃','很好吃，很漂亮'),
(null,52,11,'蛋糕很好吃','送货准时，蛋糕好吃！'),
(null,53,12,'口味不错，好吃～','谁说生日才能吃蛋糕?，就是这么任性，蛋糕非常好吃，味道纯正，孩子喜欢，下次继续购买哈'),
(null,54,13,'非常好吃','全家都很喜欢，4个大人一个小孩都够吃'),
(null,55,14,'超级喜欢','非常好吃啦 很精致的蛋糕 是值这个价格的'),
(null,56,15,'家里人都很喜欢吃','第三次购买了，6个人吃正好'),
(null,57,16,'口感不错','非常好吃，以后还会买'),
(null,58,17,'还会买','蛋糕味道不错，送货也很准时'),
(null,59,18,'挺好吃的','口味好，不腻。老公和孩子都很喜欢，下次还选他家的蛋糕，好吃！'),
(null,60,1,'很好吃','超级超级好吃，准备再定个'),
(null,61,1,'第二次买了','这个味道也不错，好评！');




#全部商品
问题:
  2.点击筛选时 全部商品 和 上面的图片 是否需要替换对应内容?
  3.小图上的遮罩层 左边换标记? 右边购物车链接到对应页面/模态框显示订购信息?

#详情页
欠缺功能:
  1.加减号可点
  3.销量排行榜?动态?轮播?热度?
  4.(商品评价,页码)

#最新活动+会员中心(空白)

欠缺功能:关键词搜索
用全部商品页?新写个模板?

#选(后台管理界面 登录页 全部商品信息页 用户列表 用户订单页)
